KISSY.add("gallery/uploader/1.4/plugins/auth/auth",function(d,m,n){function o(a){var b=-1;do a/=1024,b++;while(99<a);return Math.max(a,0.1).toFixed(1)+"kB,MB,GB,TB,PB,EB".split(",")[b]}function k(a){k.superclass.constructor.call(this,a)}var l=m.all,p="max,maxSize,allowRepeat,allowExts,required,widthHeight".split(",");d.extend(k,n,{pluginInitializer:function(a){if(!a)return!1;var b=this;b.set("uploader",a);var c=a.get("queue");b._setSwfButtonExt();b._addUploaderAttrs();c.on("add",function(a){var a=
a.file,c=b.testAllowExt(a);c&&(c=b.testMaxSize(a));c&&b.testRepeat(a);c&&b.testWidthHeight(a)});c.on("remove",function(a){"success"==a.file.status&&b.testMax()&&b.testRequired()});a.on("start",function(){a.get("disabled")&&b._maxStopUpload()});a.on("success",function(){b.testMax()});a.on("error",function(){a.set("isAllowUpload",!0)})},_addUploaderAttrs:function(){var a=this,b=a.get("uploader");d.each(p,function(c){var e=""!==a.get(c),d=e&&a.get(c)||null;e&&b.addAttr(c,{value:d,getter:function(a){return a},
setter:function(b){a.set(c,b);return b}})})},setAllowExts:function(a){if(!d.isString(a))return!1;var b=[],c=[],a=a.split(",");d.each(a,function(a){b.push("*."+a);c.push(a.toUpperCase())});b=b.join(";");c=c.join(",");return{desc:c,ext:b}},testAll:function(){return this.testRequire()&&this.testMax()},isUploaderType:function(a){var b=this.get("uploader").get("type");return a==b},testRequired:function(){return 0<this.get("uploader").get("queue").getFiles("success").length},testAllowExt:function(a){function b(a){a=
a.split(".");return a[a.length-1]}if(!d.isObject(a))return!1;var c=a.name,e=this.get("allowExts");if(!e)return!0;var g=function(a,b){var c=!1,e;d.each(a,function(a){e=RegExp("^.+."+a+"$");if(e.test(b))return c=!0});return c}(e.split(","),c);if(!g){var c=b(c),f=this.msg("allowExts"),f=d.substitute(f,{ext:c});this._fireUploaderError("allowExts",[e,f],a)}return g},testMax:function(){var a=this.get("max");if(""==a)return!0;var b=this.get("uploader"),c=b.get("queue").getFiles("success").length<a;c?(b.set("disabled",
!1),b.set("isAllowUpload",!0)):(b.set("disabled",!0),b.set("isAllowUpload",!1),b=this.msg("max"),b=d.substitute(b,{max:a}),this._fireUploaderError("max",[a,b]));return c},testMaxSize:function(a){var b=a.size,c=this.get("maxSize");if(""==c||!b)return!0;this.get("uploader");c*=1024;b=b<=c;if(!b){var e=this.msg("maxSize"),e=d.substitute(e,{maxSize:o(c),size:a.textSize});this._fireUploaderError("maxSize",[c,e],a)}return b},testRepeat:function(a){if(!d.isObject(a))return!1;var b=this,c=a.name,e=b.get("allowRepeat");
if(""===e)return!1;var g=b.get("uploader").get("queue").getFiles("success"),f=!1;d.each(g,function(d){if(d.name==c)return d.size?d.size==a.size&&b._fireUploaderError("allowRepeat",[e,b.msg("allowRepeat")],a):b._fireUploaderError("allowRepeat",[e,b.msg("allowRepeat")],a),f=!0});return f},testWidthHeight:function(a){function b(b,h){if(Number(b)!=Number(f[0])||Number(h)!=Number(f[1])){var i=c.msg("widthHeight"),i=d.substitute(i,{wh:e});c._fireUploaderError("widthHeight",[f,i],a)}else g.set("isAllowUpload",
!0),i=g.get("queue").getFileIndex(a.id),g.upload(i)}var c=this,e=c.get("widthHeight");if(""===e)return!0;var g=c.get("uploader");g.set("isAllowUpload",!1);var f=c._formatWidthHeight(e),j=a.data;if(d.isEmptyObject(j)){g.get("target").all("input").getDOMNode().select();var j=document.selection.createRange().text,h=l('<img style="filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=image);width:300px;visibility:hidden;"  />').appendTo("body").getDOMNode();h.filters.item("DXImageTransform.Microsoft.AlphaImageLoader").src=
j;b(h.offsetWidth,h.offsetHeight);l(h).remove()}else h=new FileReader,h.onload=function(a){var a=a.target.result,c=new Image;c.onload=function(){b(c.width,c.height)};c.src=a},h.readAsDataURL(j)},_formatWidthHeight:function(a){var b=[];if(!d.isString(a))return[];d.each(["x","X","_","-"],function(c){RegExp(c).test(a)&&(b=a.split(c))});return b},_setSwfButtonExt:function(){var a=this.get("uploader"),b=this.get("allowExts"),a=a.get("button");if(!this.isUploaderType("flash")||""===b)return!1;b=this.setAllowExts(b);
a&&a.set("fileFilters",b[0]);return this},_getExts:function(a){if(!d.isString(a))return!1;var b=a.split(";"),c=[],e=/^\*\./;d.each(b,function(a){a=a.replace(e,"");c.push(a.toUpperCase())});d.each(c,function(a){b.push(a)});return b},_fireUploaderError:function(a,b,c){var e=this.get("uploader"),g=e.get("queue"),a={status:-1,rule:a},f=-1;c&&(f=g.getFileIndex(c.id),d.mix(a,{file:c,index:f}));b&&d.mix(a,{msg:b[1],value:b[0],result:{}});g.fileStatus(f,"error",a);this.fire("error",a);e.fire("error",a)},
_maxStopUpload:function(){var a=this.get("uploader"),b=a.get("queue"),c=a.get("curUploadIndex");if(""==c)return!1;var e=b.get("files");a.stop();d.each(e,function(a,d){d>=c&&b.remove(d)})},msg:function(a,b){if(!d.isString(a))return this;var c=this.get("msg");return!d.isString(b)?c[a]:c[a]=b},_processRuleConfig:function(a,b){if(!d.isString(a))return this;d.isArray(b)&&this.msg(a,b[1]);return this}},{ATTRS:{pluginId:{value:"auth"},uploader:{value:""},required:{value:""},max:{value:""},allowExts:{value:""},
maxSize:{value:""},allowRepeat:{value:""},widthHeight:{value:""},msg:{value:{max:"\u6bcf\u6b21\u6700\u591a\u4e0a\u4f20{max}\u4e2a\u6587\u4ef6\uff01",maxSize:"\u6587\u4ef6\u5927\u5c0f\u4e3a{size}\uff0c\u8d85\u8fc7{maxSize}\uff01",required:"\u81f3\u5c11\u4e0a\u4f20\u4e00\u4e2a\u6587\u4ef6\uff01",allowExts:"\u4e0d\u652f\u6301{ext}\u683c\u5f0f\uff01",allowRepeat:"\u8be5\u6587\u4ef6\u5df2\u7ecf\u5b58\u5728\uff01"}}}});return k},{requires:["node","base"]});
