KISSY.add("gallery/uploader/1.4/themes/ershouUploader/index",function(c,h,g,e,f){function b(a){b.superclass.constructor.call(this,a)}var d=h.all;c.extend(b,g,{render:function(){self.get("uploader")},afterUploaderRender:function(a){var b=a.get("queue");a.get("button");var c=a.get("auth"),i=this.get("queueTarget"),j=5;c&&(j=c.getRule("max"));this.set("maxFileAllowed",j);var c=new e({msgContainer:this.get("msgContainer"),successMsgCls:this.get("successMsgCls"),hintMsgCls:this.get("hintMsgCls"),errorMsgCls:this.get("errorMsgCls")}),
g=new f(this.get("mainPicInput"),this.get("queueTarget"));this.set("message",c);this.set("setMainPic",g);"ajax"==a.get("type")&&d(this.get("queueTarget")).addClass("advance-queue");d(i).delegate("click",".J_SetMainPic",function(a){a.preventDefault();a=d(a.currentTarget).parent("li");g.setMainPic(a)});d(i).delegate("click",".J_DeleltePic",function(a){a.preventDefault();a=d(a.currentTarget).attr("data-file-id");b.remove(a)});return!0},_updateCount:function(){var a=this.get("queue").getFiles("success"),
b=this.get("maxFileAllowed")[0],d=this.get("message"),e=this.get("defaultMsg"),f=this.get("leftMsg"),a=a.length?c.substitute(f,{left:b-a.length}):c.substitute(e,{max:b});d.send(a,"hint");c.log("[Theme-ershou] file count updated. Message sent.")},_addCallback:function(a,b){var d=this.get("queue"),c=this._appendFileDom(b);d.updateFile(a,{target:c});d.fileStatus(a,"waiting");this.displayFile(!0,c);this._updateCount();return d.getFile(a)},_waitingHandler:function(a){var b=this.get("preview"),e=a.file,
f=e.target,g=d(".J_ItemPic",f);b&&b.preview(e.input,g);c.log("[Theme-ershou] preview done for file: "+a.file.id);d(f).addClass("upload-waiting")},_startHandler:function(a){d(a.file.target).replaceClass("upload-waiting","uploading")},_successHandler:function(a){var a=a.file,b=a.target,c=this.get("setMainPic");d(b).replaceClass("uploading","upload-done").attr("data-url",a.result.data.url);c.setMainPic();this._updateCount()},_removeFileHandler:function(a){a=a.file.target;this._updateCount();d(a).remove()}},
{ATTRS:{name:{value:"ershouUploader"},cssUrl:{value:"gallery/uploader/1.4/themes/ershouUploader/style.css"},fileTpl:{value:'<li id="J_LineQueue-{id}" data-file-id="{id}" data-url="{sUrl}" data-name="{name}" data-size="{textSize}"><div class="J_Wrapper wrapper"><div class="tb-pic120"><a href="javascript:void(0);"><img class="J_ItemPic" src="{sUrl}" /></a></div><div class="pic-mask"></div><div class="tips-uploading"><div class="progress-bar J_ProgressBar"><span class="progress-mask J_UploadingProgress"></span></div><p class="tips-text">\u4e0a\u4f20\u4e2d\uff0c\u8bf7\u7a0d\u5019</p></div><div class="tips-upload-success"><span class="progress-bar"></span><p class="tips-text">\u4e0a\u4f20\u6210\u529f\uff01</p></div><div class="tips-upload-error"><span class="progress-bar"></span><p>\u4e0a\u4f20\u5931\u8d25</p><p>\u8bf7\u91cd\u65b0\u5c1d\u8bd5\uff01</p></div><div class="tips-upload-waiting">\u7b49\u5f85\u4e0a\u4f20\uff0c\u8bf7\u7a0d\u5019</div><div class="upload-op-mask"></div><div class="upload-operations"><a class="J_SetMainPic set-as-main" data-file-id="{id}" href="#">\u8bbe\u4e3a\u4e3b\u56fe</a><a class="J_DeleltePic del-pic" data-file-id="{id}" href="#">\u5220\u9664</a></div></div></li>'},
plugins:{value:["preview","progressBar"]},msgContainer:{value:"#J_MsgBoxUpload"},defaultMsg:{value:"\u6700\u591a\u4e0a\u4f20{max}\u5f20\u7167\u7247\uff0c\u6bcf\u5f20\u56fe\u7247\u5c0f\u4e8e5M"},leftMsg:{value:"\u8fd8\u53ef\u4ee5\u4e0a\u4f20{left}\u5f20\u56fe\u7247\uff0c\u6bcf\u5f20\u5c0f\u4e8e5M\u3002\u4e3b\u56fe\u5c06\u5728\u641c\u7d22\u7ed3\u679c\u4e2d\u5c55\u793a\uff0c\u8bf7\u8ba4\u771f\u8bbe\u7f6e\u3002"},successMsgCls:{value:"msg-success"},hintMsgCls:{value:"msg-hint"},errorMsgCls:{value:"msg-error"},mainPicInput:{value:"#J_MainPicUrl"}}});return b},{requires:["node","gallery/uploader/1.4/themes/imageUploader/index","./message","./setMainPic"]});
KISSY.add("gallery/uploader/1.4/themes/ershouUploader/message",function(c,h){function g(b){this.config=c.mix({msgContainer:"#J_MsgBoxUpload",successMsgCls:"msg-success",hintMsgCls:"msg-hint",errorMsgCls:"msg-error"},b);c.log(f+"Constructed")}var e=h.all,f="[ershouUploader: Message] ";c.augment(g,{send:function(b,d){if(!b)return c.log(f+"You did not tell me what to show."),!1;var a=this.config.msgContainer,g=this.config[d+"MsgCls"],h=this.config.successMsgCls,i=this.config.hintMsgCls,j=this.config.errorMsgCls;
if(a)switch(d){case "success":case "hint":case "error":return e(a).html(b),e(a).replaceClass([h,i,j].join(" "),g),!0;default:return c.log(f+"type error"),!1}}});return g},{requires:["node"]});
KISSY.add("gallery/uploader/1.4/themes/ershouUploader/setMainPic",function(c,h){function g(b,d){b=e(b);d=e(d);if(!b||0>=b.length)return c.log(f+"cannot find mainPicInput, SetMainPic function disabled."),!1;if(!d||0>=d.length)return c.log(f+"cannot find queue container"),!1;this.queueContainer=d;this.input=b}var e=h.all,f="[LineQueue: setMainPic] ";c.augment(g,{setMainPic:function(b){var d=e("li",this.queueContainer);c.isString(b)&&c.each(d,function(a){if(e(a).attr("data-url")==b)return b=a,!0});var a=
this.getMainPic(),b=e(b);if(!b||0>=b.length)if(d[0]){if(0<a.length)return c.log(f+"Already have a main pic. Since you do not tell me which one to set as main pic, I will do nothing."),a;c.log(f+"No li element specified. I will set the first pic as main pic.");b=d[0]}else return c.log(f+"There is no pic. I cannot set any pic as main pic. So I will empty the main pic input."),e(this.input).val(""),null;var d=e(".J_Wrapper",b),g=e('<span class="main-pic-logo">\u4e3b\u56fe</span>'),h=e(b).attr("data-url");0<a.length&&
(e(a).removeClass("main-pic"),e(".main-pic-logo",a).remove());e(b).addClass("main-pic");e(g).appendTo(d);e(this.input).val(h);c.log(f+"write main pic url to :"+h);return b},getMainPic:function(){return e(this.queueContainer).children(".main-pic")},getMainPicUrl:function(){return e(this.input).val()}});return g},{requires:["node"]});
