KISSY.add("gallery/uploader/1.4/base",function(e,i,g,f,d,b,a,c,h){function j(c){j.superclass.constructor.call(this,c)}e.mix(j,{type:{AUTO:"auto",IFRAME:"iframe",AJAX:"ajax",FLASH:"flash"},event:{SELECT:"select",ADD:"add",START:"start",PROGRESS:"progress",COMPLETE:"complete",SUCCESS:"success",UPLOAD_FILES:"uploadFiles",CANCEL:"cancel",ERROR:"error",REMOVE:"remove",RESTORE:"restore"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",SUCCESS:"success",CANCEL:"cancel",ERROR:"error"}});e.extend(j,
i,{upload:function(c){if(!e.isNumber(c))return!1;var a=this.get("uploadType"),b=this.get("type"),h=this.get("queue"),d=h.get("files")[c],f;if(!e.isPlainObject(d))return e.log("[uploader]:\u961f\u5217\u4e2d\u4e0d\u5b58\u5728id\u4e3a"+c+"\u7684\u6587\u4ef6"),!1;if(""!=this.get("curUploadIndex"))return alert("\u7b2c"+this.get("curUploadIndex")+"\u6587\u4ef6\u6b63\u5728\u4e0a\u4f20\uff0c\u8bf7\u4e0a\u4f20\u5b8c\u540e\u518d\u64cd\u4f5c\uff01"),!1;f=d.input.id||d.input;"ajax"==b&&(f=d.data);if("error"===d.status)return!1;this.fire(j.event.START,{index:c,file:d});if(!this.get("isAllowUpload"))return!1;this.set("curUploadIndex",c);h.fileStatus(c,
j.status.START);a.upload(f)},cancel:function(c){var a=this.get("uploadType"),b=this.get("queue"),h=j.status,d=b.fileStatus(c);e.isNumber(c)&&d!=h.SUCCESS?(a.stop(),b.fileStatus(c,h.CANCEL)):(a.stop(),this._continueUpload());return this},stop:function(){this.set("uploadFilesStatus","");this.cancel();return this},uploadFiles:function(c){e.isString(c)||(c=j.status.WAITING);this.set("uploadFilesStatus",c);this._uploaderStatusFile(c);return this},_uploaderStatusFile:function(c){c=this.get("queue").getIndexs(c);
if(!c.length)return this.set("uploadFilesStatus",""),this.fire(j.event.UPLOAD_FILES),!1;this.upload(c[0]);return this},isSupportAjax:function(){var c=!1;try{FormData&&(c=!0)}catch(a){c=!1}return c},isSupportFlash:function(){var c=e.UA.fpv();return e.isArray(c)&&0<c.length},_renderUploaderCore:function(){var c=this,a=c.get("type"),a=c.getUploadType(a);if(!a)return!1;var b={action:c.get("action"),data:c.get("data"),dataType:"json"},h=c.get("button");c.get("type")==j.type.FLASH&&e.mix(b,{swfUploader:h.get("swfUploader")});
b.fileDataName=c.get("name");b=new a(b);a=a.event;b.on(a.SUCCESS,c._uploadCompleteHanlder,c);b.on(a.ERROR,function(a){c.fire(event.ERROR,{status:a.status,result:a.result})},c);if(a.PROGRESS)b.on(a.PROGRESS,c._uploadProgressHandler,c);b.on(a.STOP,c._uploadStopHanlder,c);c.set("uploadType",b);return b},getUploadType:function(c){var a=this,b=j.type,h;c==b.AUTO&&(c=[b.AJAX,b.IFRAME]);e.isArray(c)&&0<c.length?e.each(c,function(c){if(h=a._getType(c))return!1}):h=a._getType(c);return h},_getType:function(c){var a=
j.type,h=this.isSupportAjax(),g=this.isSupportFlash();switch(c){case a.IFRAME:a=f;break;case a.AJAX:a=h&&d||!1;break;case a.FLASH:a=g&&b||!1;break;default:return e.log("[uploader]:type\u53c2\u6570\u4e0d\u5408\u6cd5"),!1}a&&e.log("[uploader]:\u4f7f\u7528"+c+"\u4e0a\u4f20\u65b9\u5f0f");this.set("type",c);return a},_renderButton:function(){var b,h;h=this.get("type");b=this.get("target");var d=this.get("multiple"),f=this.get("disabled"),d={name:this.get("name"),multiple:d,disabled:f};h==j.type.FLASH?(h=c,e.mix(d,{size:this.get("swfSize")})):h=a;b=new h(b,
d);b.on("change",this._select,this);b.render();this.set("button",b);return b},_renderQueue:function(){var c=this,a=new h;a.set("uploader",c);a.on("add",function(a){c.fire(j.event.ADD,a)});a.on("remove",function(a){c.fire(j.event.REMOVE,a)});c.set("queue",a);return a},_select:function(c){var a=this,b=a.get("autoUpload"),h=a.get("queue"),d=a.get("curUploadIndex"),f=c.files;e.each(f,function(a){a.size||(a.size=0);a.name||(a.name=a.fileName||"");a.input=c.input||a});f=a._processExceedMultiple(f);a.fire(j.event.SELECT,
{files:f});if(!a.get("isAllowUpload"))return!1;h.add(f,function(){""==d&&b&&a.uploadFiles()})},_processExceedMultiple:function(c){var a=this.get("multipleLen");return 0>a||!e.isArray(c)||!c.length?c:e.filter(c,function(c,b){return b<a})},_uploadCompleteHanlder:function(c){var c=c.result,a,b=j.event,h=this.get("queue"),d=this.get("curUploadIndex");if(!e.isObject(c))return!1;h.updateFile(d,{result:c});a=Number(c.status);1===a?(h.fileStatus(d,j.status.SUCCESS),this._success(c.data),this.fire(b.SUCCESS,
{index:d,file:h.getFile(d),result:c})):(h.fileStatus(d,j.status.ERROR,{msg:c.msg||c.message||"",result:c}),this.fire(b.ERROR,{status:a,result:c,index:d,file:h.getFile(d)}));this.set("curUploadIndex","");this.fire(b.COMPLETE,{index:d,file:h.getFile(d),result:c});this._continueUpload()},_uploadStopHanlder:function(){var c=this.get("queue"),a=this.get("curUploadIndex");c.fileStatus(a,j.status.CANCEL);this.set("curUploadIndex","");this.fire(j.event.CANCEL,{index:a})},_continueUpload:function(){var c=
this.get("uploadFilesStatus");""!=c&&this._uploaderStatusFile(c)},_uploadProgressHandler:function(c){var a=this.get("queue"),b=this.get("curUploadIndex"),h=a.getFile(b);e.mix(c,{file:h});a.fileStatus(b,j.status.PROGRESS,c);this.fire(j.event.PROGRESS,c)},_success:function(c){if(!e.isObject(c))return!1;var c=c.url,a=this.get("curUploadIndex"),b=this.get("queue");if(!e.isString(c))return!1;b.updateFile(a,{sUrl:c})}},{ATTRS:{button:{value:{}},queue:{value:{}},curUploadIndex:{value:""},uploadType:{value:{}},
urlsInput:{value:""},uploadFilesStatus:{value:""},swfSize:{value:{}}}});return j},{requires:"base,node,./type/iframe,./type/ajax,./type/flash,./button/base,./button/swfButton,./queue".split(",")});
KISSY.add("gallery/uploader/1.4/button/base",function(e,i,g){function f(b,a){a=e.merge({target:d(b)},a);f.superclass.constructor.call(this,a)}var d=i.all;e.mix(f,{event:{beforeShow:"beforeShow",afterShow:"afterShow",beforeHide:"beforeHide",afterHide:"afterHide",beforeRender:"beforeRender",afterRender:"afterRender",CHANGE:"change"},getFileName:function(b){return b.replace(/.*(\/|\\)/,"")}});e.extend(f,g,{render:function(){var b=this.get("target");if(!1===this.fire(f.event.beforeRender))return e.log("[Uploader-Button] button render was prevented."),
!1;if(null==b)return e.log("[Uploader-Button] Cannot find target!"),!1;this._createInput();this.fire(f.event.afterRender);return this},show:function(){this.get("target").show();this.fire(f.event.afterShow);return f},hide:function(){this.get("target").hide();this.fire(f.event.afterHide);return f},reset:function(){var b=this.get("inputContainer");d(b).remove();this.set("inputContainer","");this.set("fileInput","");this._createInput();return this},_createInput:function(){var b=this.get("target"),a=this.get("name"),
c=this.get("tpl");if(!e.isString(a)||!e.isString(c))return e.log("[Uploader-Button] No name or tpl specified."),!1;a=e.substitute(c,{name:a});a=d(a);d(a).appendTo(b);b=d(a).children("input");6==e.UA.ie&&b.css("fontSize","400px");d(b).on("change",this._changeHandler,this);this.set("fileInput",b);this.set("inputContainer",a);this._setDisabled(this.get("disabled"));this._setMultiple(this.get("multiple"));return a},_changeHandler:function(b){var a=this.get("fileInput"),c=d(a).val(),b=b.target.files,h=
[];if(""==c)return e.log("[Uploader-Button] No file selected."),!1;b?e.each(b,function(c){e.isObject(c)&&h.push({name:c.name,type:c.type,size:c.size,data:c})}):h.push({name:f.getFileName(c)});this.fire(f.event.CHANGE,{files:h,input:a.getDOMNode()});this.reset()},_setDisabled:function(b){var a=this.get("cls").disabled,c=this.get("target"),h=this.get("fileInput");if(!c.length||!e.isBoolean(b))return!1;b?(c.addClass(a),d(h).hide()):(c.removeClass(a),d(h).show());return b},_setMultiple:function(b){var a=
this.get("fileInput");if(!a.length)return!1;b&&a.attr("multiple","multiple")||a.removeAttr("multiple");return b}},{ATTRS:{target:{value:null},fileInput:{value:""},inputContainer:{value:""},tpl:{value:'<div class="file-input-wrapper" style="overflow: hidden;"><input type="file" name="{name}" hidefocus="true" class="file-input" /></div>'},name:{value:"fileInput",setter:function(b){this.get("fileInput")&&d(this.get("fileInput")).attr("name",b);return b}},disabled:{value:!1,setter:function(b){this._setDisabled(b);
return b}},multiple:{value:!0,setter:function(b){this._setMultiple(b);return b}},cls:{value:{disabled:"uploader-button-disabled"}}}});return f},{requires:["node","base"]});
KISSY.add("gallery/uploader/1.4/button/swfButton",function(e,i,g,f){function d(a,c){c=e.merge({target:b(a)},c);d.superclass.constructor.call(this,c)}var b=i.all;e.mix(d,{event:{RENDER:"render",CHANGE:"change",MOUSE_OVER:"mouseOver",MOUSE_DOWN:"mouseDown",MOUSE_UP:"mouseUp",MOUSE_OUT:"mouseOut",CLICK:"click"}});e.extend(d,g,{render:function(){var a=this,c=a.get("target"),b,e=a.get("multiple"),f=a.get("fileFilters");c.css("position","relative");a.set("swfWrapper",a._createSwfWrapper());a._setFlashSizeConfig();
b=a._initSwfUploader();b.on("contentReady",function(){b.browse(e,f);a._bindBtnEvent();b.on("fileSelect",a._changeHandler,a);a._setDisabled(a.get("disabled"));a.fire(d.event.RENDER)},a)},_createSwfWrapper:function(){var a=this.get("target"),c=this.get("tpl"),h=""!=this.get("swfWrapperId")&&this.get("swfWrapperId")||"swf-uploader-wrapper-"+e.guid(),c=e.substitute(c,{id:h});this.set("swfWrapperId",h);return b(c).appendTo(a)},_initSwfUploader:function(){var a=this.get("flash"),c=this.get("swfWrapperId"),
b;e.mix(a,{id:"swfUploader"+e.guid()});try{b=new f(c,a),this.set("swfUploader",b)}catch(d){}return b},_bindBtnEvent:function(){var a=this,c=d.event,b=a.get("swfUploader");if(!b)return!1;e.each(c,function(c){b.on(c,function(){a.fire(c)},a)});return a},_setFlashSizeConfig:function(){var a=this.get("flash"),c=this.get("target"),b=this.get("size");e.isEmptyObject(b)?e.mix(a.attrs,{width:c.innerWidth(),height:c.innerHeight()}):e.mix(a.attrs,b);this.set("flash",a)},_changeHandler:function(a){this.fire(d.event.CHANGE,
{files:a.fileList})},_setDisabled:function(a){var c=this.get("swfUploader"),b=this.get("cls").disabled,d=this.get("target"),f=this.get("swfWrapper");if(!c||!e.isBoolean(a))return!1;a?(d.addClass(b),f.css("top","-3000px")):(d.removeClass(b),f.css("top",0));return a},show:function(){this.get("target").show()},hide:function(){this.get("target").hide()}},{ATTRS:{target:{value:""},swfWrapper:{value:""},swfWrapperId:{value:""},tpl:{value:'<div id="{id}" class="uploader-button-swf" style="position: absolute;top:0;left:0;z-index:2000;"></div>'},
multiple:{value:!0,setter:function(a){var c=this.get("swfUploader");c&&c.multifile(a);return a}},fileFilters:{value:[],setter:function(a){var c=this.get("swfUploader");e.isObject(a)&&(a=[a]);c&&e.isArray(a)&&e.later(function(){c.filter(a)},800);return a}},disabled:{value:!1,setter:function(a){this.get("swfUploader")&&this._setDisabled(a);return a}},cls:{value:{disabled:"uploader-button-disabled"}},size:{value:{}},flash:{value:{src:"http://a.tbcdn.cn/s/kissy/gallery/uploader/1.4/plugins/ajbridge/uploader.swf",
id:"swfUploader",params:{bgcolor:"#fff",wmode:"transparent"},attrs:{},hand:!0,btn:!0}},swfUploader:{value:""}}});return d},{requires:["node","base","../plugins/ajbridge/uploader"]});
KISSY.add("gallery/uploader/1.4/index",function(e,i,g,f){var d=i.all,b=f.extend([g],{constructor:function(a,c){b.superclass.constructor.call(this,c);this.set("target",a);this._init()},_init:function(){if(!this.get("target").length)return e.log("\u76ee\u6807\u5143\u7d20\u4e0d\u5b58\u5728\uff01"),!1;this._replaceBtn();this._renderButton();this._renderQueue();this._renderUploaderCore();return this},_replaceBtn:function(){var a=this.get("target");if(!a.length)return!1;var c=a[0].defaultValue||"\u4e0a\u4f20\u6587\u4ef6",c=e.substitute(this.get("btnTpl"),{text:c}),
c=d(c).insertAfter(a);!this.get("name")&&a.attr("name")&&this.set("name",a.attr("name"));this.set("_oldInput",a.clone());a.remove();this.set("target",c);return c},use:function(a,c){var b=this,d;if(!a)return b;if(!b.get("target").length)return e.log("use():\u76ee\u6807\u5143\u7d20\u4e0d\u5b58\u5728\uff01"),!1;var f=a.split(",");e.each(f,function(c,a){/\//.test(c)||(f[a]="gallery/uploader/1.4/plugins/"+c+"/"+c)});e.use(f.join(","),function(){var a=e.makeArray(arguments).slice(1);e.each(a,function(a){var f=e.merge(c,{uploader:b});d=new a(f);
d.pluginInitializer&&d.pluginInitializer(b);b.get("plugins").push(d)})});return b},theme:function(a,c){var b=this.get("theme");if(b)return e.log("\u4e0d\u652f\u6301\u91cd\u65b0\u6e32\u67d3\u4e3b\u9898\uff01"),this;e.isString(a)?b=this._initTheme(a,c||{}):e.isObject(a)&&(b=a,b.render());this.set("theme",b);return this},_initTheme:function(a,c){var b=this,d=b._getThemeName(a);if(!c.queueTarget)return e.log("\u4e3b\u9898\u914d\u7f6e\u7f3a\u5c11queueTarget\uff01"),!1;e.use(d,function(e,f){e.mix(c,{uploader:b,queue:b.get("queue"),buttonTarget:b.get("target")});d=new f(c);d.on("init",function(){d.render();
b.fire("themeRender",{theme:d,name:a})})})},_getThemeName:function(a){var c=a,b=this.get("supportThemes");e.each(b,function(b){b==a&&(c="gallery/uploader/1.4/themes/"+a)});return c+="/index"}},{ATTRS:{target:{value:"",getter:function(a){return d(a)}},fileInput:{value:"",getter:function(){return this.get("target").all(".file-input")}},theme:{value:""},supportThemes:{value:"default,imageUploader,daogouUploader,ershouUploader,loveUploader,refundUploader,singleImageUploader".split(",")},btnTpl:{value:'<a href="javascript:void(0)" class="g-u ks-uploader-button"><span class="btn-text">{text}</span></a>'},
button:{value:{}},queue:{value:{}},type:{value:"auto"},multiple:{value:!1,setter:function(a){var c=this.get("button");!e.isEmptyObject(c)&&e.isBoolean(a)&&c.set("multiple",a);return a}},multipleLen:{value:-1},disabled:{value:!1,setter:function(a){var c=this.get("button");!e.isEmptyObject(c)&&e.isBoolean(a)&&c.set("disabled",a);return a}},action:{value:"",setter:function(a){var c=this.get("uploadType");c&&c.set("action",a);return a}},data:{value:{},setter:function(a){e.isObject(a)&&this.get("uploadType").set("data",
a);return a}},isAllowUpload:{value:!0},autoUpload:{value:!0},filter:{value:"",setter:function(a){var c=this.get("uploadType");c&&c.set("filter",a);return a}},curUploadIndex:{value:""},uploadType:{value:""},swfSize:{value:{}}}},"Uploader");return b},{requires:["node","./base","rich-base"]});
KISSY.add("gallery/uploader/1.4/plugins/ajbridge/ajbridge",function(e,i){function g(c,h,j){var c=c.replace(f,""),h=i._normalize(h||{}),n=this,c=f+c,l=function(c){1>c.status?n.fire("failed",{data:c}):(e.mix(n,c),(!c.dynamic||!h.src)&&n.activate())};h.id=h.id||e.guid(d);g.instances[h.id]=n;h.src&&(h.params.allowscriptaccess="always",h.params.flashvars=e.merge(h.params.flashvars,{jsEntry:a,swfID:h.id}));j?n.__args=[c,h,l]:e.later(i.add,b,!1,i,[c,h,l])}var f="#",d="ks-ajb-",b=100,a="KISSY.AJBridge.eventHandler";
e.mix(g,{version:"1.0.15",instances:{},eventHandler:function(c,a){var b=g.instances[c];b&&b.__eventHandler(c,a)},augment:function(c,a){e.isString(a)&&(a=[a]);e.isArray(a)&&e.each(a,function(a){c.prototype[a]=function(){try{return this.callSWF(a,e.makeArray(arguments))}catch(c){this.fire("error",{message:c})}}})}});e.augment(g,e.EventTarget,{init:function(){this.__args&&(i.add.apply(i,this.__args),this.__args=null,delete this.__args)},__eventHandler:function(c,a){var b=a.type;a.id=c;switch(b){case "log":e.log(a.message);
break;default:this.fire(b,a)}},callSWF:function(c,a){a=a||[];try{if(this.swf[c])return this.swf[c].apply(this.swf,a)}catch(b){var e="";0!==a.length&&(e="'"+a.join("','")+"'");return(new Function("self","return self.swf."+c+"("+e+");"))(this)}}});g.augment(g,["activate","getReady","getCoreVersion"]);return window.AJBridge=e.AJBridge=g},{requires:["flash"]});
KISSY.add("gallery/uploader/1.4/plugins/ajbridge/uploader",function(e,i,g){function f(d,b){var b=b||{},a={};e.each(["ds","dsp","btn","hand"],function(c){c in b&&(a[c]=b[c])});b.params=b.params||{};b.params.flashvars=e.merge(b.params.flashvars,a);f.superclass.constructor.call(this,d,b)}e.extend(f,g);g.augment(f,"setFileFilters,filter,setAllowMultipleFiles,multifile,browse,upload,uploadAll,cancel,getFile,removeFile,lock,unlock,setBtnMode,useHand,clear".split(","));f.version="1.0.1";g.Uploader=f;return g.Uploader},
{requires:["flash","./ajbridge"]});
KISSY.add("gallery/uploader/1.4/plugins/auth/auth",function(e,i,g){function f(c){var a=-1;do c/=1024,a++;while(99<c);return Math.max(c,0.1).toFixed(1)+"kB,MB,GB,TB,PB,EB".split(",")[a]}function d(c){d.superclass.constructor.call(this,c)}var b=i.all,a="max,maxSize,allowRepeat,allowExts,required,widthHeight".split(",");e.extend(d,g,{pluginInitializer:function(c){if(!c)return!1;var a=this;a.set("uploader",c);var b=c.get("queue");a._setSwfButtonExt();a._addUploaderAttrs();c.testMax=function(){return a.testMax()};
c.testRequired=function(){return a.testRequired()};c.test=function(){return a.testMax()&&a.testRequired()};b.on("add",function(c){var c=c.file,b=a.testAllowExt(c);b&&(b=a.testMaxSize(c));b&&a.testRepeat(c);b&&a.testWidthHeight(c)});b.on("remove",function(c){"success"==c.file.status&&a.testMax()&&a.testRequired()});c.on("start",function(){c.get("disabled")&&a._maxStopUpload()});c.on("success",function(){a.testMax()});c.on("error",function(){c.set("isAllowUpload",!0)})},_addUploaderAttrs:function(){var c=
this,b=c.get("uploader");e.each(a,function(a){var e=""!==c.get(a),d=e&&c.get(a)||null;e&&b.addAttr(a,{value:d,getter:function(c){return c},setter:function(b){c.set(a,b);return b}})})},setAllowExts:function(c){if(!e.isString(c))return!1;var a=[],b=[],c=c.split(",");e.each(c,function(c){a.push("*."+c);b.push(c.toUpperCase())});a=a.join(";");b=b.join(",");return{desc:b,ext:a}},testAll:function(){return this.testRequire()&&this.testMax()},isUploaderType:function(c){var a=this.get("uploader").get("type");
return c==a},testRequired:function(){return 0<this.get("uploader").get("queue").getFiles("success").length},testAllowExt:function(c){function a(c){c=c.split(".");return c[c.length-1]}if(!e.isObject(c))return!1;var b=c.name,d=this.get("allowExts");if(!d)return!0;var f=function(c,a){var b=!1,d;e.each(c,function(c){d=RegExp("^.+."+c+"$");if(d.test(a))return b=!0});return b}(d.split(","),b);if(!f){var b=a(b),g=this.msg("allowExts"),g=e.substitute(g,{ext:b});this._fireUploaderError("allowExts",[d,g],c)}return f},
testMax:function(){var c=this.get("max");if(""==c)return!0;var a=this.get("uploader"),b=a.get("queue").getFiles("success").length<c;b?(a.set("disabled",!1),a.set("isAllowUpload",!0)):(a.set("disabled",!0),a.set("isAllowUpload",!1),a=this.msg("max"),a=e.substitute(a,{max:c}),this._fireUploaderError("max",[c,a]));return b},testMaxSize:function(c){var a=c.size,b=this.get("maxSize");if(""==b||!a)return!0;this.get("uploader");b*=1024;a=a<=b;if(!a){var d=this.msg("maxSize"),d=e.substitute(d,{maxSize:f(b),
size:c.textSize});this._fireUploaderError("maxSize",[b,d],c)}return a},testRepeat:function(a){if(!e.isObject(a))return!1;var b=this,d=a.name,f=b.get("allowRepeat");if(""===f)return!1;var g=b.get("uploader").get("queue").getFiles("success"),i=!1;e.each(g,function(e){if(e.name==d)return e.size?e.size==a.size&&b._fireUploaderError("allowRepeat",[f,b.msg("allowRepeat")],a):b._fireUploaderError("allowRepeat",[f,b.msg("allowRepeat")],a),i=!0});return i},testWidthHeight:function(a){function d(b,h){if(Number(b)!=
Number(i[0])||Number(h)!=Number(i[1])){var k=f.msg("widthHeight"),k=e.substitute(k,{wh:g});f._fireUploaderError("widthHeight",[i,k],a)}else l.set("isAllowUpload",!0),k=l.get("queue").getFileIndex(a.id),l.upload(k)}var f=this,g=f.get("widthHeight");if(""===g)return!0;var l=f.get("uploader");l.set("isAllowUpload",!1);var i=f._formatWidthHeight(g),m=a.data;if(e.isEmptyObject(m)){l.get("target").all("input").getDOMNode().select();var m=document.selection.createRange().text,k=b('<img style="filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=image);width:300px;visibility:hidden;"  />').appendTo("body").getDOMNode();
k.filters.item("DXImageTransform.Microsoft.AlphaImageLoader").src=m;d(k.offsetWidth,k.offsetHeight);b(k).remove()}else k=new FileReader,k.onload=function(a){var a=a.target.result,c=new Image;c.onload=function(){d(c.width,c.height)};c.src=a},k.readAsDataURL(m)},_formatWidthHeight:function(a){var b=[];if(!e.isString(a))return[];e.each(["x","X","_","-"],function(e){RegExp(e).test(a)&&(b=a.split(e))});return b},_setSwfButtonExt:function(){var a=this.get("uploader"),b=this.get("allowExts"),a=a.get("button");
if(!this.isUploaderType("flash")||""===b)return!1;b=this.setAllowExts(b);a&&a.set("fileFilters",b[0]);return this},_getExts:function(a){if(!e.isString(a))return!1;var b=a.split(";"),d=[],f=/^\*\./;e.each(b,function(a){a=a.replace(f,"");d.push(a.toUpperCase())});e.each(d,function(a){b.push(a)});return b},_fireUploaderError:function(a,b,d){var f=this.get("uploader"),g=f.get("queue"),a={status:-1,rule:a},i=-1;d&&(i=g.getFileIndex(d.id),e.mix(a,{file:d,index:i}));b&&e.mix(a,{msg:b[1],value:b[0],result:{}});
g.fileStatus(i,"error",a);this.fire("error",a);f.fire("error",a)},_maxStopUpload:function(){var a=this.get("uploader"),b=a.get("queue"),d=a.get("curUploadIndex");if(""==d)return!1;var f=b.get("files");a.stop();e.each(f,function(a,c){c>=d&&b.remove(c)})},msg:function(a,b){if(!e.isString(a))return this;var d=this.get("msg");return!e.isString(b)?d[a]:d[a]=b},_processRuleConfig:function(a,b){if(!e.isString(a))return this;e.isArray(b)&&this.msg(a,b[1]);return this}},{ATTRS:{pluginId:{value:"auth"},uploader:{value:""},
required:{value:""},max:{value:""},allowExts:{value:""},maxSize:{value:""},allowRepeat:{value:""},widthHeight:{value:""},msg:{value:{max:"\u6bcf\u6b21\u6700\u591a\u4e0a\u4f20{max}\u4e2a\u6587\u4ef6\uff01",maxSize:"\u6587\u4ef6\u5927\u5c0f\u4e3a{size}\uff0c\u8d85\u8fc7{maxSize}\uff01",required:"\u81f3\u5c11\u4e0a\u4f20\u4e00\u4e2a\u6587\u4ef6\uff01",allowExts:"\u4e0d\u652f\u6301{ext}\u683c\u5f0f\uff01",allowRepeat:"\u8be5\u6587\u4ef6\u5df2\u7ecf\u5b58\u5728\uff01"}}}});return d},{requires:["node","base"]});KISSY.add("gallery/uploader/1.4/plugins/coverPic/coverPic",function(e,i,g){function f(){}e.extend(f,g,{pluginInitializer:function(e){if(!e)return!1}},{ATTRS:{}});return f},{requires:["node","base"]});
KISSY.add("gallery/uploader/1.4/plugins/filedrop/filedrop",function(e,i,g){var f=i.all,d=e.UA,b=function(c){b.superclass.constructor.call(this,c);this.set("mode",a())},a=function(){if(7<=d.webkit||3.6<=d.firefox)return"supportDrop";if(d.ie)return"notSupportDropIe";if(7>d.webkit||3.6>d.firefox)return"notSupportDrop"};e.mix(b,{event:{AFTER_DROP:"afterdrop"}});e.extend(b,g,{pluginInitializer:function(a){var b=this,d=b.get("mode");if("flash"==a.get("type"))return e.log("flash\u4e0a\u4f20\u65b9\u5f0f\u4e0d\u652f\u6301\u62d6\u62fd\uff01"),b.set("isSupport",
!1),!1;if("supportDrop"!=d)return e.log("\u8be5\u6d4f\u89c8\u5668\u4e0d\u652f\u6301\u62d6\u62fd\u4e0a\u4f20\uff01"),b.set("isSupport",!1),!1;d=a.get("target");b.set("target",d);b._createDropArea().on("click",b._clickHandler,b);a.on("afterDisabledChange",function(a){b[a.newVal&&"hide"||"show"]()});b.fire("render",{buttonTarget:b.get("buttonWrap")})},show:function(){this.get("dropContainer").show()},hide:function(){this.get("dropContainer").hide()},_createDropArea:function(){var a=this,b=f(a.get("target")),d=a.get("mode"),d=e.substitute(a.get("tpl")[d],{name:a.get("name")}),
d=f(d),g=d.all(".J_ButtonWrap");d.appendTo(b);d.on("dragover",function(a){a.stopPropagation();a.preventDefault()});d.on("drop",function(b){b.stopPropagation();b.preventDefault();a._dropHandler(b)});a.set("dropContainer",d);a.set("buttonWrap",g);a._setStyle();return d},_setStyle:function(){var a=this.get("dropContainer");if(!a.length)return!1;a.parent().css("position","relative");a.css({position:"absolute",top:"0",left:"0",width:"100%",height:"100%",zIndex:"1000"})},_clickHandler:function(a){f(a.target);
this.get("uploader").get("button").get("fileInput").fire("click")},_dropHandler:function(a){var d=b.event,a=a.originalEvent.dataTransfer.files,f=[],g=this.get("uploader");if(!a.length||""==g)return!1;e.each(a,function(a){e.isObject(a)&&f.push({name:a.name,type:a.type,size:a.size,data:a})});this.fire(d.AFTER_DROP,{files:f});g._select({files:f})}},{ATTRS:{pluginId:{value:"filedrop"},target:{value:""},uploader:{value:""},dropContainer:{value:""},isSupport:{value:!0},tpl:{value:{supportDrop:'<div class="drop-wrapper"></div>',
notSupportDropIe:'<div class="drop-wrapper"><p>\u60a8\u7684\u6d4f\u89c8\u5668\u53ea\u652f\u6301\u4f20\u7edf\u7684\u56fe\u7247\u4e0a\u4f20\uff0c</p><p class="suggest J_ButtonWrap">\u63a8\u8350\u4f7f\u7528chrome\u6d4f\u89c8\u5668\u6216firefox\u6d4f\u89c8\u5668</p></div>',notSupportDrop:'<div class="drop-wrapper"><p>\u60a8\u7684\u6d4f\u89c8\u5668\u53ea\u652f\u6301\u4f20\u7edf\u7684\u56fe\u7247\u4e0a\u4f20\uff0c</p><p class="suggest J_ButtonWrap">\u63a8\u8350\u5347\u7ea7\u60a8\u7684\u6d4f\u89c8\u5668</p></div>'}},name:{value:"",setter:function(){}},disabled:{value:!1,setter:function(a){this._setDisabled(a);return a}},cls:{disabled:"drop-area-disabled"}}});return b},{requires:["node","base"]});
KISSY.add("gallery/uploader/1.4/plugins/imageZoom/imageZoom",function(e,i,g,f){function d(a){d.superclass.constructor.call(this,a)}var b=i.all;e.extend(d,g,{pluginInitializer:function(a){if(!a)return!1;a.on("success",this._successHandler,this)},_successHandler:function(a){var a=a.file,c=a.result.url,d=b(".J_Pic_"+a.id);d.attr("data-original-url",c);d.addClass("J_ImgDD");this._renderIMGDD(a.target)},_renderIMGDD:function(a){if(!a||!a.length)return!1;(new f).add(a,".J_ImgDD")}},{ATTRS:{pluginId:{value:"imageZoom"}}});
return d},{requires:["node","base","gallery/image-dd/1.0/index"]});
KISSY.add("gallery/uploader/1.4/plugins/preview/preview",function(e,i,g,f){function d(a,b){if(!a)return!1;"filter"!=c?a.src=b||h:(a.src=h,b&&(b=b.replace(/[)'"%]/g,function(a){return escape(escape(a))}),a.filters.item("DXImageTransform.Microsoft.AlphaImageLoader").src=b));return!0}function b(a){this.config=e.mix({maxWidth:40,maxHeight:40},a);b.superclass.constructor.call(this,a)}var a=document,c=function(){var a="";if("undefined"===typeof window.FileReader)switch(e.UA.shell){case "firefox":a="domfile";
break;case "ie":switch(e.UA.ie){case 6:a="simple";break;default:a="filter"}}else a="html5";return a}(),h=8>e.UA.ie?"http://a.tbcdn.cn/p/fp/2011a/assets/space.gif":"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";e.extend(b,f,{pluginInitializer:function(){},preview:function(b,f){var b=i.get(b),f=i.get(f),h=this,g=function(){h.fire(void 0,{data:h.data,mode:c});f&&(d(f,h.data),h.fire("showed",{img:f}))};h.data=void 0;if(b){e.log("[Plugin: Preview] One file selected. Getting data...");
switch(c){case "domfile":h.data=b.files[0].getAsDataURL();break;case "filter":b.select();try{h.data=a.selection.createRange().text}catch(m){e.log("[Plugin: Preview] Get image data error, the error is: "),e.log(m,"dir")}finally{a.selection.empty()}h.data||(h.data=b.value);break;case "html5":var k=new FileReader;k.onload=function(a){h.data=a.target.result;g()};k.onerror=function(){e.log("[Plugin: Preview] File Reader Error. Your browser may not fully support html5 file api","warning");h.fire("error")};
b.files&&k.readAsDataURL(b.files[0]);break;default:h.data=b.value}h.data?g():"html5"!=c&&(e.log("[Plugin: Preview] Retrive Data error."),d(f),h.fire("error"))}else e.log("[Plugin: Preview] File Input Element does not exists.");return h.data}},{ATTRS:{pluginId:{value:"preview"}}});return b},{requires:["dom","event","base"]});
KISSY.add("gallery/uploader/1.4/plugins/proBars/proBars",function(e,i,g,f){function d(a){d.superclass.constructor.call(this,a)}var b=i.all;e.mix(d,{event:{RENDER:"render"}});e.extend(d,g,{pluginInitializer:function(a){if(!a)return!1;var c=this;if("iframe"==a.get("type"))return a.on("success",function(a){b(".J_ProgressBar_"+a.file.id).hide()}),!1;a.on("start",function(a){c.add(a.file.id)});a.on("progress",c._uploaderProgressHandler,c);a.on("success",c._uploaderSuccessHandler,c);c.fire(d.event.RENDER)},
_uploaderProgressHandler:function(a){var b=a.file.id,a=Math.ceil(100*(a.loaded/a.total));this.get("bars")[b].set("value",a)},_uploaderSuccessHandler:function(a){a=a.file.id;this.get("bars")[a].set("value",100)},add:function(a){if(!e.isString(a))return!1;var c=b(".J_ProgressBar_"+a),d=this.get("isHide"),g=new f(c,{width:this.get("width")});if(d)g.on("change",function(a){100==a.value&&e.later(function(){c.hide()},500)});g.render();return this.get("bars")[a]=g}},{ATTRS:{bars:{value:{}},width:{value:"auto"},
isHide:{value:!0},duration:{value:0.3},speed:{value:0.2}}});return d},{requires:["node","base","gallery/uploader/1.4/plugins/proBars/progressBar"]});
KISSY.add("gallery/uploader/1.4/plugins/proBars/progressBar",function(e,i,g){function f(b,a){a=e.merge({wrapper:d(b)},a);f.superclass.constructor.call(this,a)}var d=i.all;e.mix(f,{tpl:{DEFAULT:'<div class="ks-progress-bar-value" data-value="{value}"></div>'},cls:{PROGRESS_BAR:"ks-progress-bar",VALUE:"ks-progress-bar-value"},event:{RENDER:"render",CHANGE:"change",SHOW:"show",HIDE:"hide"}});e.extend(f,g,{render:function(){var b=this.get("wrapper"),a=this.get("width");if(!b.length)return!1;"auto"==a&&
(a=b.parent().width());b.width(a);b.addClass(f.cls.PROGRESS_BAR);this._addAttr();!this.get("visible")&&this.hide();this.set("bar",this._create());this.fire(f.event.RENDER)},show:function(){var b=this;b.get("wrapper").fadeIn(b.get("duration"),function(){b.set("visible",!0);b.fire(f.event.SHOW,{visible:!0})})},hide:function(){var b=this;b.get("wrapper").fadeOut(b.get("duration"),function(){b.set("visible",!1);b.fire(f.event.HIDE,{visible:!1})})},_create:function(){var b=this.get("wrapper"),a=this.get("value"),
c=this.get("tpl"),a=e.substitute(c,{value:a});b.html("");return d(a).appendTo(b)},_addAttr:function(){var b=this.get("wrapper"),a=this.get("value");b.attr("role","progressbar");b.attr("aria-valuemin",0);b.attr("aria-valuemax",100);b.attr("aria-valuenow",a);return this}},{ATTRS:{wrapper:{value:""},bar:{value:""},width:{value:"auto"},value:{value:0,setter:function(b){var a=this,c=a.get("wrapper"),d=a.get("bar"),e=a.get("speed"),g;100<b&&(b=100);0>b&&(b=0);g=c.width()*(b/100);d.animate({width:g+"px"},
e,"none",function(){c.attr("aria-valuenow",b);d.attr("data-value",b);a.fire(f.event.CHANGE,{value:b,width:g})});return b}},visible:{value:!0},duration:{value:0.3},tpl:{value:f.tpl.DEFAULT},speed:{value:0.2}}});return f},{requires:["node","base"]});
KISSY.add("gallery/uploader/1.4/plugins/tagConfig/tagConfig",function(e,i,g){function f(a){f.superclass.constructor.call(this,a)}var d="autoUpload,postData,action,multiple,multipleLen,uploadType,disabled".split(","),b="max,maxSize,allowRepeat,allowExts,required,widthHeight".split(",");e.extend(f,g,{pluginInitializer:function(a){if(!a)return!1;a=a.get("_oldInput");if(!a)return!1;this.set("input",a);this._setUploaderConfig();this._setAuthConfig()},_setUploaderConfig:function(){var a=this.get("input"),
b,f=this.get("uploader");e.each(d,function(d){if(b=a.attr(d)){switch(d){case "postData":d="data";b=e.JSON.parse(b);break;case "uploadType":d="type";break;case "autoUpload":b="true"==b}f.set(d,b)}})},_setAuthConfig:function(){var a=this.get("input"),c=this.get("uploader").getPlugin("auth");if(!c)return!1;var d,f;e.each(b,function(b){if(d=a.attr(b)){switch(b){case "allowRepeat":d="true"==d;break;case "maxSize":d=Number(d)}c.set(b,d);(f=a.attr(b+"-"+f))&&c.msg(b,f)}})}},{ATTRS:{pluginId:{value:"tagConfig"},
input:{value:""}}});return f},{requires:["node","base"]});
KISSY.add("gallery/uploader/1.4/plugins/urlsInput/urlsInput",function(e,i,g){function f(b){f.superclass.constructor.call(this,b)}var d=i.all;e.extend(f,g,{pluginInitializer:function(b){if(!b)return!1;this.set("uploader",b);b.on("success",this._uploadSuccessHandler,this);b.get("queue").on("remove",this._fileRemoveHandler,this);this.get("autoRestore")&&this.restore()},_uploadSuccessHandler:function(b){b=b.result;if(!e.isObject(b))return!1;this.add(b.url);return this},_fileRemoveHandler:function(b){b.file.sUrl&&
this.remove(b.file.sUrl)},add:function(b){if(!e.isString(b))return e.log("[uploader-urlsInput]:add()\u7684url\u53c2\u6570\u4e0d\u5408\u6cd5\uff01"),!1;var a=this.get("urls"),c=this.isExist(b);""==a[0]&&(a=[]);if(c)return e.log("[uploader-urlsInput]:add()\uff0c\u6587\u4ef6\u8def\u5f84\u5df2\u7ecf\u5b58\u5728\uff01"),this;a.push(b);this.set("urls",a);this._val();return this},remove:function(b){if(!b)return!1;var a=this.get("urls"),c=this.isExist(b),d=RegExp(b);if(!c)return e.log("[uploader-urlsInput]:remove()\uff0c\u4e0d\u5b58\u5728\u8be5\u6587\u4ef6\u8def\u5f84\uff01"),!1;a=e.filter(a,function(a){return!d.test(a)});this.set("urls",
a);this._val();return a},parse:function(){var b=this.get("target");if(b){var b=d(b).val(),a=this.get("split");if(""==b)return[];b=b.split(a);this.set("urls",b);return b}e.log("[uploader-urlsInput]:cannot find urls input.");return[]},_val:function(){var b=this.get("urls"),a=this.get("target"),c=this.get("split"),b=b.join(c);a.val(b);return b},isExist:function(b){var a=!1,c=this.get("urls"),d=RegExp(b);if(!c.length)return!1;e.each(c,function(b){if(d.test(b))return a=!0});return a},restore:function(){var b=
this.get("uploader").get("queue"),a=this._getRestoreData();if(!a.length)return!1;e.each(a,function(a){var a=b.add(a),d=a.id,e=b.getFileIndex(d);b.fileStatus(e,"success",{index:e,id:d,file:a})})},_getRestoreData:function(){var b=this.parse(),a=[];e.each(b,function(b){a.push({name:b,type:"restore",url:b,sUrl:b,result:{status:1,name:b,url:b}})});return a}},{ATTRS:{pluginId:{value:"urlsInput"},uploader:{value:""},urls:{value:[]},split:{value:",",setter:function(b){this._val();return b}},autoRestore:{value:!0},
target:{value:"",getter:function(b){return d(b)}}}});return f},{requires:["node","base"]});
KISSY.add("gallery/uploader/1.4/queue",function(e,i,g){function f(d){f.superclass.constructor.call(this,d)}e.mix(f,{event:{ADD:"add",ADD_FILES:"addFiles",REMOVE:"remove",CLEAR:"clear",FILE_STATUS:"statusChange",UPDATE_FILE:"updateFile"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"},FILE_ID_PREFIX:"file-"});e.extend(f,g,{add:function(d,b){var a=this,c={};if(0<d.length){var c=[],f=a.get("uploader"),g=a.get("files").length,
i=0<f.get("max");e.each(d,function(b,d){i?f.get("max")>=g+d+1&&c.push(a._addFile(b)):c.push(a._addFile(b))})}else c=a._addFile(d);b&&b.call(a);return c},_addFile:function(d,b){if(!e.isObject(d))return e.log("[uploader-queue]:_addFile()\u53c2\u6570file\u4e0d\u5408\u6cd5\uff01"),!1;var a=this._setAddFileData(d),c=this.getFileIndex(a.id),h=this.get("fnAdd");e.isFunction(h)&&(a=h(c,a));this.fire(f.event.ADD,{index:c,file:a,uploader:this.get("uploader")});b&&b.call(this,c,a);return a},remove:function(d,b){var a=this.get("files"),c;
e.isString(d)&&(d=this.getFileIndex(d));c=a[d];if(!e.isObject(c))return e.log("[uploader-queue]:remove()\u4e0d\u5b58\u5728index\u4e3a"+d+"\u7684\u6587\u4ef6\u6570\u636e"),!1;a=e.filter(a,function(a,b){return b!==d});this.set("files",a);this.fire(f.event.REMOVE,{index:d,file:c});b&&b.call(this,d,c);return c},clear:function(){function d(){a=b.get("files");if(!a.length)return b.fire(f.event.CLEAR),!1;b.remove(0,function(){d()})}var b=this,a;d()},fileStatus:function(d,b,a){if(!e.isNumber(d))return!1;var c=this.getFile(d);this.get("theme");var h;
if(!c)return!1;h=c.status;if(!b)return h;if(h==b)return this;this.updateFile(d,{status:b});this.fire(f.event.FILE_STATUS,{index:d,status:b,args:a,file:c});return this},getFile:function(d){if(!e.isNumber(d))return!1;d=this.get("files")[d];e.isPlainObject(d)||(d={});return d},getFileIndex:function(d){var b=this.get("files"),a=-1;e.each(b,function(b,e){if(b.id==d)return a=e,!0});return a},updateFile:function(d,b){if(!e.isNumber(d))return!1;if(!e.isObject(b))return e.log("[uploader-queue]:updateFile()\u7684data\u53c2\u6570\u6709\u8bef\uff01"),
!1;var a=this.get("files"),c=this.getFile(d);if(!c)return!1;e.mix(c,b);a[d]=c;this.set("files",a);this.fire(f.event.UPDATE_FILE,{index:d,file:c});return c},getIndexs:function(d){var b=this.get("files"),a,c=[];if(!b.length)return c;e.each(b,function(b,f){e.isObject(b)&&(a=b.status,a==d&&c.push(f))});return c},getFiles:function(d){var b=this.get("files"),a=[];if(!b.length)return[];e.each(b,function(b){b&&b.status==d&&a.push(b)});return a},_setAddFileData:function(d){var b=this.get("files");if(!e.isObject(d))return e.log("[uploader-queue]:_updateFileData()\u53c2\u6570file\u4e0d\u5408\u6cd5\uff01"),
!1;d.id||(d.id=e.guid(f.FILE_ID_PREFIX));d.size&&e.convertByteSize&&(d.textSize=e.convertByteSize(d.size));d.status="waiting";b.push(d);return d}},{ATTRS:{fnAdd:{value:""},files:{value:[]},uploader:{value:""}}});return f},{requires:["node","base"]});
KISSY.add("gallery/uploader/1.4/theme",function(e,i,g){function f(b){f.superclass.constructor.call(this,b);this._init()}var d=i.all;e.extend(f,g,{_init:function(){var b=this;b._addThemeCssName();b._tplFormHtml();b._usePlugins();b._bind();b._setAuth();b._LoaderCss(function(){b._restore();b.fire("init")})},render:function(){},_selectHandler:function(){},_addHandler:function(){},_removeHandler:function(){},_waitingHandler:function(){},_startHandler:function(){},_progressHandler:function(){},_successHandler:function(){},
_errorHandler:function(){},_restore:function(){var b=this,a=b.get("uploader"),c=a.getPlugin("urlsInput");if(!c||!c.get("autoRestore"))return!1;c=a.get("queue").get("files");if(!c.length)return!1;e.each(c,function(c,d){c.status="success";a.fire("add",{file:c,index:d});b._renderHandler("_successHandler",{file:c,result:c.result});b._hideStatusDiv(c)});return b},_addThemeCssName:function(){var b=this.get("name"),a=d(this.get("queueTarget")),c=d(this.get("buttonTarget"));if(""==b)return!1;a.length&&a.addClass("ks-uploader-queue "+
b+"-queue");c.addClass(b+"-button");return this},_bind:function(){var b=this,a=b.get("uploader"),c="add,remove,select,start,progress,success,error,complete".split(",");a.on(c[0],function(c){var d=b._appendFileDom(c.file);a.get("queue").updateFile(c.index,{target:d})});a.on(c[1],function(a){b._removeFileDom(a.file)});e.each(c,function(c){a.on(c,function(a){b._renderHandler("_"+a.type+"Handler",a)})})},_renderHandler:function(b,a){var c=this.get("extend"),d=this[b];this._setStatusVisibility(a.file);
e.isObject(c)&&e.isFunction(c[b])?c[b].call(this,a):d&&d.call(this,a)},_setStatusVisibility:function(b){if(!e.isObject(b))return this;this._hideStatusDiv(b);var a=b.status,c=b.target,b=c.all("."+a+"-status");b.length&&b.show();e.each("waiting,start,uploading,progress,error,success".split(","),function(a){c.removeClass(a)});c.addClass(a);return this},_hideStatusDiv:function(b){if(!e.isObject(b))return!1;b.target.all(".status").hide()},_LoaderCss:function(b){var a=this,c=a.get("cssUrl");if(""==c)return b&&
b.call(a),!1;e.use(c,function(){e.log(c+"\u52a0\u8f7d\u6210\u529f\uff01");b&&b.call(a)})},_appendFileDom:function(b){var a=this.get("fileTpl"),c=d(this.get("queueTarget"));if(!c.length)return!1;a=e.substitute(a,b);return d(a).hide().appendTo(c).fadeIn(0.4).data("data-file",b)},_removeFileDom:function(b){if(!e.isObject(b))return!1;var a=b.target;if(!a||!a.length)return!1;a.fadeOut(0.4,function(){a.remove()})},_usePlugins:function(){var b=this.get("use");if(""==b)return!1;this.get("uploader").use(b);return this},_tplFormHtml:function(){var b=
this,a=b.get("fileTpl"),c=d(b.get("queueTarget"));if(!c.length)return!1;c.all("script").each(function(c){"text/uploader-theme"==c.attr("type")&&(a=c.html(),b.set("fileTpl",a))});return a},_setAuth:function(){var b=this.get("authMsg");if(e.isEmptyObject(b))return!1;var a=this.get("uploader").getPlugin("auth");if(!a)return!1;a.set("msg",b);b=this.get("allowExts");""!==b&&a.set("allowExts",b)}},{ATTRS:{name:{value:""},use:{value:""},cssUrl:{value:""},fileTpl:{value:""},extend:{value:""},authMsg:{value:{}},
queueTarget:{value:""},queue:{value:""},uploader:{value:""}}});return f},{requires:["node","base"]});
KISSY.add("gallery/uploader/1.4/type/ajax",function(e,i,g){function f(d){f.superclass.constructor.call(this,d)}e.mix(f,{event:e.merge(g.event,{PROGRESS:"progress"})});e.extend(f,g,{upload:function(d){if(!d)return e.log("[uploader-AjaxType]:upload()\uff0cfileData\u53c2\u6570\u6709\u8bef\uff01"),!1;this._setFormData();this._addFileData(d);this.send();return this},stop:function(){var d=this.get("xhr");if(!e.isObject(d))return e.log("[uploader-AjaxType]:stop()\uff0cio\u503c\u9519\u8bef\uff01"),!1;d.abort();this.fire(f.event.STOP);return this},send:function(){var d=
this,b=d.get("action"),a=d.get("formData"),c=new XMLHttpRequest;c.upload.addEventListener("progress",function(a){d.fire(f.event.PROGRESS,{loaded:a.loaded,total:a.total})});c.onload=function(){var a=d._processResponse(c.responseText);d.fire(f.event.SUCCESS,{result:a})};c.open("POST",b,!0);a.append("type","ajax");c.send(a);d._setFormData();d.set("xhr",c);return d},_setFormData:function(){try{this.set("formData",new FormData),this._processData()}catch(d){e.log("[uploader-AjaxType]:something error when reset FormData."),
e.log(d,"dir")}},_processData:function(){var d=this.get("data"),b=this.get("formData");e.each(d,function(a,c){b.append(c,a)});this.set("formData",b)},_addFileData:function(d){if(!e.isObject(d))return e.log("[uploader-AjaxType]:_addFileData()\uff0cfile\u53c2\u6570\u6709\u8bef\uff01"),!1;var b=this.get("formData"),a=this.get("fileDataName");b.append(a,d);this.set("formData",b)}},{ATTRS:{formData:{value:""},ajaxConfig:{value:{type:"post",processData:!1,cache:!1,dataType:"json",contentType:!1}},xhr:{value:""},fileDataName:{value:""},
form:{value:{}},fileInput:{value:""}}});return f},{requires:["node","./base"]});
KISSY.add("gallery/uploader/1.4/type/base",function(e,i,g){function f(d){f.superclass.constructor.call(this,d)}e.mix(f,{event:{START:"start",STOP:"stop",SUCCESS:"success",ERROR:"error"}});e.extend(f,g,{upload:function(){},stop:function(){},_processResponse:function(d){var b=this.get("filter"),a={};""!=b&&(d=b.call(this,d));if(e.isString(d))try{a=e.JSON.parse(d),a=this._fromUnicode(a)}catch(c){d+="\uff0c\u8fd4\u56de\u7ed3\u679c\u96c6responseText\u683c\u5f0f\u4e0d\u5408\u6cd5\uff01",e.log(d),this.fire("error",{status:-1,result:{msg:d}})}else e.isObject(d)&&
(a=this._fromUnicode(d));e.log("\u670d\u52a1\u5668\u7aef\u8f93\u51fa\uff1a"+e.JSON.stringify(a));return a},_fromUnicode:function(d){function b(a){e.each(a,function(c,d){e.isObject(a[d])?b(a[d]):a[d]=e.isString(c)&&e.fromUnicode(c)||c})}if(!e.isObject(d))return d;b(d);return d}},{ATTRS:{action:{value:""},data:{value:{}},filter:{value:""}}});return f},{requires:["node","base"]});
KISSY.add("gallery/uploader/1.4/type/flash",function(e,i,g){function f(d){f.superclass.constructor.call(this,d);this.isHasCrossdomain();this._init()}e.mix(f,{event:e.merge(g.event,{SWF_READY:"swfReady",PROGRESS:"progress"})});e.extend(f,g,{_init:function(){var d=this,b=d.get("swfUploader");if(!b)return e.log("[uploader-FlashType]:swfUploader\u5bf9\u8c61\u4e3a\u7a7a\uff01"),!1;b.on("contentReady",function(){d.fire(f.event.SWF_READY)},d);b.on("uploadStart",d._uploadStartHandler,d);b.on("uploadProgress",d._uploadProgressHandler,
d);b.on("uploadCompleteData",d._uploadCompleteDataHandler,d);b.on("uploadError",d._uploadErrorHandler,d)},upload:function(d){var b=this.get("swfUploader"),a=this.get("action"),c=this.get("data"),f=this.get("fileDataName");f||(f="Filedata");this.set("uploadingId",d);e.mix(c,{type:"flash"});b.upload(d,a,"POST",c,f);return this},stop:function(){var d=this.get("swfUploader"),b=this.get("uploadingId");""!=b&&(d.cancel(b),this.fire(f.event.STOP,{id:b}));return this},_uploadStartHandler:function(d){this.fire(f.event.START,
{file:d.file})},_uploadProgressHandler:function(d){e.mix(d,{loaded:d.bytesLoaded,total:d.bytesTotal});e.log("[uploader-FlashType]:\u5df2\u7ecf\u4e0a\u4f20\u5b57\u8282\u6570\u4e3a\uff1a"+d.bytesLoaded);this.fire(f.event.PROGRESS,{loaded:d.loaded,total:d.total})},_uploadCompleteDataHandler:function(d){d=this._processResponse(d.data);this.set("uploadingId","");this.fire(f.event.SUCCESS,{result:d})},_uploadErrorHandler:function(d){this.set("uploadingId","");this.fire(f.event.ERROR,{msg:d.msg})},isHasCrossdomain:function(){e.io({url:"http://"+location.hostname+
"/crossdomain.xml",dataType:"xml",error:function(){e.log("\u7f3a\u5c11crossdomain.xml\u6587\u4ef6\u6216\u8be5\u6587\u4ef6\u4e0d\u5408\u6cd5\uff01")}})}},{ATTRS:{action:{value:"",getter:function(d){if(!/^http/.test(d))var b=location.href.split("/"),d=e.filter(b,function(a,c){return c<b.length-1}).join("/")+"/"+d;return d}},swfUploader:{value:""},uploadingId:{value:""}}});return f},{requires:["node","./base"]});
KISSY.add("gallery/uploader/1.4/type/iframe",function(e,i,g){function f(b){f.superclass.constructor.call(this,b)}var d=i.all;e.mix(f,{tpl:{IFRAME:'<iframe src="javascript:false;" name="{id}" id="{id}" border="no" width="1" height="1" style="display: none;" />',FORM:'<form method="post" enctype="multipart/form-data" action="{action}" target="{target}" style="visibility: hidden;">{hiddenInputs}</form>',HIDDEN_INPUT:'<input type="hidden" name="{name}" value="{value}" />'},event:e.mix(g.event,{CREATE:"create",
REMOVE:"remove"})});e.extend(f,g,{upload:function(b){b=d(b);if(!b.length)return!1;this.fire(f.event.START,{input:b});this.set("fileInput",b);this._create();b=this.get("form");if(!b)return e.log("[uploader-iframeType]:form\u8282\u70b9\u4e0d\u5b58\u5728\uff01"),!1;b.getDOMNode().submit()},stop:function(){this.get("iframe").attr("src",'javascript:"<html></html>";');this._remove();this.fire(f.event.STOP);this.fire(f.event.ERROR,{status:"abort",msg:"\u4e0a\u4f20\u5931\u8d25\uff0c\u539f\u56e0\uff1aabort"});return this},dataToHidden:function(b){if(!e.isObject(b)||e.isEmptyObject(b))return"";
var a="",c=this.get("tpl").HIDDEN_INPUT;if(!e.isString(c))return"";for(var d in b)a+=e.substitute(c,{name:d,value:b[d]});return a},_createIframe:function(){var b="ks-uploader-iframe-"+e.guid(),a=this.get("tpl"),c=a.IFRAME,f=this.get("iframe");if(!e.isEmptyObject(f))return f;if(!e.isString(c))return e.log("[uploader-iframeType]:iframe\u7684\u6a21\u677f\u4e0d\u5408\u6cd5\uff01"),!1;if(!e.isString(b))return e.log("[uploader-iframeType]:id\u5fc5\u987b\u5b58\u5728\u4e14\u4e3a\u5b57\u7b26\u4e32\u7c7b\u578b\uff01"),!1;a=e.substitute(a.IFRAME,{id:b});a=d(a);a.on("load",this._iframeLoadHandler,this);
d("body").append(a);this.set("id",b);this.set("iframe",a);return a},_iframeLoadHandler:function(b){var a=b.target,b=f.event.ERROR,a=a.contentDocument||window.frames[a.id].document;if(!a||!a.body)return this.fire(b,{msg:"\u670d\u52a1\u5668\u7aef\u8fd4\u56de\u6570\u636e\u6709\u95ee\u9898\uff01"}),!1;b=a.body.innerHTML;if(""==b)return!1;b=this._processResponse(b);this.fire(f.event.SUCCESS,{result:b});this._remove()},_createForm:function(){var b=this.get("id"),a=this.get("tpl").FORM,c=this.get("data"),f=this.get("action"),g=this.get("fileInput");if(!e.isString(a))return e.log("[uploader-iframeType]:form\u6a21\u677f\u4e0d\u5408\u6cd5\uff01"),
!1;if(!e.isString(f))return e.log("[uploader-iframeType]:action\u53c2\u6570\u4e0d\u5408\u6cd5\uff01"),!1;c=this.dataToHidden(c);c+=this.dataToHidden({type:"iframe"});b=e.substitute(a,{action:f,target:b,hiddenInputs:c});g=d(b).append(g);d("body").append(g);this.set("form",g);return g},_create:function(){var b=this._createIframe(),a=this._createForm();this.fire(f.event.CREATE,{iframe:b,form:a})},_remove:function(){var b=this.get("form");if(!b)return!1;b.remove();this.reset("form");this.fire(f.event.REMOVE,{form:b})}},{ATTRS:{tpl:{value:f.tpl},
id:{value:"ks-uploader-iframe-"+e.guid()},iframe:{value:{}},form:{value:""},fileInput:{value:""}}});return f},{requires:["node","./base"]});
