KISSY.add("gallery/form/1.3/uploader/auth/base",function(c,j,h){function f(a,b){b=c.merge({uploader:a},b);f.superclass.constructor.call(this,b);this._init()}var d=d||c;c.mix(f,{event:{ERROR:"error"},defaultRules:{allowExts:[{desc:"JPG,JPEG,PNG,GIF,BMP",ext:"*.jpg;*.jpeg;*.png;*.gif;*.bmp"},"\u4e0d\u652f\u6301{ext}\u683c\u5f0f\u7684\u6587\u4ef6\u4e0a\u4f20\uff01"],required:[!1,"\u5fc5\u987b\u81f3\u5c11\u4e0a\u4f20\u4e00\u4e2a\u6587\u4ef6\uff01"],max:[3,"\u6bcf\u6b21\u6700\u591a\u4e0a\u4f20{max}\u4e2a\u6587\u4ef6\uff01"],maxSize:[1E3,"\u6587\u4ef6\u5927\u5c0f\u4e3a{size}\uff0c\u6587\u4ef6\u592a\u5927\uff01"],allowRepeat:[!1,"\u8be5\u6587\u4ef6\u5df2\u7ecf\u5b58\u5728\uff01"]}});c.extend(f,h,{_init:function(){var a=this,b=a.get("uploader"),c=b.get("queue");
if(""==b)return d.log("[uploader-auth]:uploader\u4e0d\u53ef\u4ee5\u4e3a\u7a7a\uff01"),!1;a._setSwfButtonExt();a._addUploaderAttrs();b.testMax=function(){return a.testMax()};b.testRequired=function(){return a.testRequired()};b.test=function(){return a.testMax()&&a.testRequired()};c.on("add",function(b){b=b.file;"restore"!=b.type&&(a.testAllowExt(b),a.testMaxSize(b),a.testRepeat(b))});c.on("remove",function(b){"success"==b.file.status&&a.testMax()&&a.testRequired()});c.on("statusChange",function(c){c=c.status;"start"==c&&b.get("disabled")&&
a._maxStopUpload();"success"==c&&a.testMax()});b.on("error",function(){b.set("isAllowUpload",!0)})},_addUploaderAttrs:function(){var a=this,b=a.get("uploader"),e=a.get("rules");c.each(f.defaultRules,function(g,d){var i=!c.isUndefined(e[d]),l=i&&e[d][0]||null;i||(e[d]=[l,g[1]]);b.addAttr(d,{value:l,getter:function(b){"allowExts"==d&&(b=a.getAllowExts(b));return b},setter:function(b){var c=a.get("rules");debugger;"allowExts"==d&&(b=a.setAllowExts(b));return c[d][0]=b}})});c.each(e,function(c,e){b.addAttr(e,
{value:c[0],getter:function(b){"allowExts"==e&&(b=a.getAllowExts(b));return b},setter:function(b){var c=a.get("rules");"allowExts"==e&&(b=a.setAllowExts(b));return c[e][0]=b}})})},setAllowExts:function(a){if(!c.isString(a))return!1;var b=[],e=[],a=a.split(",");c.each(a,function(a){b.push("*."+a);e.push(a.toUpperCase())});b=b.join(";");e=e.join(",");return{desc:e,ext:b}},getAllowExts:function(a){if(!c.isObject(a))return a;var a=a.ext.split(";"),b=[];c.each(a,function(a){b.push(a.replace("*.",""))});
return b.join(",")},testAll:function(){return this.testRequire()&&this.testMax()},getRule:function(a){return this.get("rules")[a]},isUploaderType:function(a){var b=this.get("uploader").get("type");return a==b},testRequire:function(){var a=this.get("uploader").get("urlsInput").get("urls"),b=this.getRule("required")||this.getRule("require"),a=0<a.length;if(!b||!b[0])return!0;a||(c.log("[uploader-auth]:"+b[1]),this._fireUploaderError("required",b));return a},testRequired:function(){return this.testRequire()},
testAllowExt:function(a){function b(a){a=a.split(".");return a[a.length-1]}if(!c.isObject(a))return!1;var e=a.name,g=this.getRule("allowExts"),d=[],i;if(!c.isArray(g))return!1;d=this._getExts(g[0].ext);i=function(a){var b=!1,g;c.each(d,function(c){g=RegExp("^.+."+c+"$");if(g.test(a))return b=!0});return b}(e);i||(e=b(e),e=c.substitute(g[1],{ext:e}),this._fireUploaderError("allowExts",[g[0],e],a));return i},testMax:function(){var a=this.get("uploader"),b=a.get("queue").getFiles("success").length,e=
this.getRule("max");if(e)return(b=b<e[0])?(a.set("disabled",!1),a.set("isAllowUpload",!0)):(a.set("disabled",!0),a.set("isAllowUpload",!1),a=c.substitute(e[1],{max:e[0]}),this._fireUploaderError("max",[e[0],a])),b},testMaxSize:function(a){var b=a.size,e=this.getRule("maxSize");if(e){var g=1024*Number(e[0]),b=b<=g;b||(g=c.substitute(e[1],{maxSize:c.convertByteSize(g),size:a.textSize}),this._fireUploaderError("maxSize",[e[0],g],a));return b}},testRepeat:function(a){if(!c.isObject(a))return!1;var b=
this,e=a.name,g=b.getRule("allowRepeat");if(g){var d=g[0],i=b.get("uploader").get("queue").getFiles("success"),l=!1;if(d)return!1;c.each(i,function(c){if(c.name==e&&c.size==a.size)return b._fireUploaderError("allowRepeat",g,a),l=!0});return l}},_setSwfButtonExt:function(){var a=this.get("uploader"),b=this.getRule("allowExts"),a=a.get("button");if(!this.isUploaderType("flash")||!c.isArray(b))return!1;a&&a.set("fileFilters",b[0]);return this},_getExts:function(a){if(!c.isString(a))return!1;var b=a.split(";"),
e=[],g=/^\*\./;c.each(b,function(a){a=a.replace(g,"");e.push(a.toUpperCase())});c.each(e,function(a){b.push(a)});return b},_fireUploaderError:function(a,b,e){var g=this.get("uploader"),d=g.get("queue"),a={status:-1,rule:a},i=-1;e&&(i=d.getFileIndex(e.id),c.mix(a,{file:e,index:i}));b&&c.mix(a,{msg:b[1],value:b[0],result:{}});d.fileStatus(i,"error",a);this.fire(f.event.ERROR,a);g.fire("error",a)},_maxStopUpload:function(){var a=this.get("uploader"),b=a.get("queue"),e=a.get("curUploadIndex");if(""==
e)return!1;var g=b.get("files");a.stop();c.each(g,function(a,c){c>=e&&b.remove(c)})}},{ATTRS:{uploader:{value:""},rules:{value:f.defaultRules}}});return f},{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/base",function(c,j,h,f,d,a,b,e,g,k){function i(a){i.superclass.constructor.call(this,a)}c.mix(i,{type:{AUTO:"auto",IFRAME:"iframe",AJAX:"ajax",FLASH:"flash"},event:{RENDER:"render",SELECT:"select",START:"start",PROGRESS:"progress",COMPLETE:"complete",SUCCESS:"success",UPLOAD_FILES:"uploadFiles",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"}});
c.extend(i,j,{render:function(){var a=this,b=a.get("serverConfig"),g=a.get("type"),e=a.getUploadType(g),g=e.event,d;if(!e)return!1;d=a._renderButton();a.set("urlsInput",a._renderUrlsInput());a._renderQueue();a.get("type")==i.type.FLASH&&c.mix(b,{swfUploader:d.get("swfUploader")});b.fileDataName=a.get("name");b=new e(b);b.on(g.SUCCESS,a._uploadCompleteHanlder,a);b.on(g.ERROR,function(b){a.fire(event.ERROR,{status:b.status,result:b.result})},a);if(g.PROGRESS)b.on(g.PROGRESS,a._uploadProgressHandler,
a);b.on(g.STOP,a._uploadStopHanlder,a);a.set("uploadType",b);a.fire(i.event.RENDER);return a},upload:function(a){if(!c.isNumber(a))return!1;var b=this.get("uploadType"),g=this.get("type"),e=this.get("queue"),d=e.get("files")[a],k;if(!c.isPlainObject(d))return c.log("[uploader]:\u961f\u5217\u4e2d\u4e0d\u5b58\u5728id\u4e3a"+a+"\u7684\u6587\u4ef6"),!1;if(""!=this.get("curUploadIndex"))return alert("\u7b2c"+this.get("curUploadIndex")+"\u6587\u4ef6\u6b63\u5728\u4e0a\u4f20\uff0c\u8bf7\u4e0a\u4f20\u5b8c\u540e\u518d\u64cd\u4f5c\uff01"),!1;k=d.input.id||d.input;"ajax"==g&&(k=d.data);if("error"===d.status)return!1;this.fire(i.event.START,
{index:a,file:d});if(!this.get("isAllowUpload"))return!1;this.set("curUploadIndex",a);e.fileStatus(a,i.status.START);b.upload(k)},cancel:function(a){var b=this.get("uploadType"),g=this.get("queue"),e=i.status,d=g.fileStatus(a);c.isNumber(a)&&d!=e.SUCCESS?(b.stop(),g.fileStatus(a,e.CANCEL)):(b.stop(),this._continueUpload());return this},stop:function(){this.set("uploadFilesStatus","");this.cancel();return this},uploadFiles:function(a){c.isString(a)||(a=i.status.WAITING);this.set("uploadFilesStatus",
a);this._uploaderStatusFile(a);return this},_uploaderStatusFile:function(a){a=this.get("queue").getIndexs(a);if(!a.length)return this.set("uploadFilesStatus",""),this.fire(i.event.UPLOAD_FILES),!1;this.upload(a[0]);return this},isSupportAjax:function(){var a=!1;try{FormData&&(a=!0)}catch(b){a=!1}return a},isSupportFlash:function(){var a=c.UA.fpv();return c.isArray(a)&&0<a.length},getUploadType:function(a){var b=this,g=i.type,e;a==g.AUTO&&(a=[g.AJAX,g.FLASH,g.IFRAME]);c.isArray(a)&&0<a.length?c.each(a,
function(a){if(e=b._getType(a))return!1}):e=b._getType(a);return e},_getType:function(g){var e=i.type,k=this.isSupportAjax(),f=this.isSupportFlash();switch(g){case e.IFRAME:e=d;break;case e.AJAX:e=k&&a||!1;break;case e.FLASH:e=f&&b||!1;break;default:return c.log("[uploader]:type\u53c2\u6570\u4e0d\u5408\u6cd5"),!1}e&&c.log("[uploader]:\u4f7f\u7528"+g+"\u4e0a\u4f20\u65b9\u5f0f");this.set("type",g);return e},_renderButton:function(){var a,b;b=this.get("type");a=this.get("target");var d=this.get("multiple"),k=this.get("disabled"),d={name:this.get("name"),
multiple:d,disabled:k};b==i.type.FLASH?(b=g,c.mix(d,{size:this.get("swfSize")})):b=e;a=new b(a,d);a.on("change",this._select,this);a.render();this.set("button",a);return a},_renderQueue:function(){var a=new k,b=this.get("urlsInput");if(!c.isObject(a))return c.log("[uploader]:queue\u53c2\u6570\u4e0d\u5408\u6cd5"),!1;a.set("uploader",this);a.on("remove",function(a){a.file.sUrl&&b&&b.remove(a.file.sUrl)});this.set("queue",a);return a},_select:function(a){var b=this,g=b.get("autoUpload"),e=b.get("queue"),d=b.get("curUploadIndex"),
k=a.files;c.each(k,function(b){b.size||(b.size=0);b.name||(b.name=b.fileName||"");b.input=a.input||b});k=b._processExceedMultiple(k);b.fire(i.event.SELECT,{files:k});if(!b.get("isAllowUpload"))return!1;e.add(k,function(){""==d&&g&&b.uploadFiles()})},_processExceedMultiple:function(a){var b=this.get("multipleLen");return 0>b||!c.isArray(a)||!a.length?a:c.filter(a,function(a,c){return c<b})},_renderUrlsInput:function(){var a=this.get("button").get("target"),b=this.get("urlsInputName"),a=new f(a,{name:b});
a.render();return a},_uploadCompleteHanlder:function(a){var a=a.result,b,g=i.event,e=this.get("queue"),d=this.get("curUploadIndex");if(!c.isObject(a))return!1;e.updateFile(d,{result:a});b=Number(a.status);1===b?(e.fileStatus(d,i.status.SUCCESS),this._success(a.data),this.fire(g.SUCCESS,{index:d,file:e.getFile(d),result:a})):(e.fileStatus(d,i.status.ERROR,{msg:a.msg||a.message||"",result:a}),this.fire(g.ERROR,{status:b,result:a,index:d,file:e.getFile(d)}));this.set("curUploadIndex","");this.fire(g.COMPLETE,
{index:d,file:e.getFile(d),result:a});this._continueUpload()},_uploadStopHanlder:function(){var a=this.get("queue"),b=this.get("curUploadIndex");a.fileStatus(b,i.status.CANCEL);this.set("curUploadIndex","");this.fire(i.event.CANCEL,{index:b})},_continueUpload:function(){var a=this.get("uploadFilesStatus");""!=a&&this._uploaderStatusFile(a)},_uploadProgressHandler:function(a){var b=this.get("queue"),g=this.get("curUploadIndex"),e=b.getFile(g);c.mix(a,{file:e});b.fileStatus(g,i.status.PROGRESS,a);this.fire(i.event.PROGRESS,
a)},_success:function(a){if(!c.isObject(a))return!1;var a=a.url,b=this.get("urlsInput"),g=this.get("curUploadIndex"),e=this.get("queue");if(!c.isString(a)||!c.isObject(b))return!1;e.updateFile(g,{sUrl:a});b.add(a)},restore:function(a){var b=this.get("queue");this.get("urlsInput");a||(a=this._getRestoreData());if(!a.length)return!1;c.each(a,function(a){var a=b.add(a),c=a.id,g=b.getFileIndex(c);b.fileStatus(g,"success",{index:g,id:c,file:a})})},_getRestoreData:function(){var a=this.get("urlsInput").parse(),
b=[];c.each(a,function(a){b.push({name:a,type:"restore",url:a,sUrl:a,result:{status:1,data:{name:a,url:a}}})});return b}},{ATTRS:{button:{value:{}},queue:{value:{}},type:{value:i.type.AUTO},multiple:{value:!0,setter:function(a){var b=this.get("button");!c.isEmptyObject(b)&&c.isBoolean(a)&&b.set("multiple",a);return a}},multipleLen:{value:-1},disabled:{value:!1,setter:function(a){var b=this.get("button");!c.isEmptyObject(b)&&c.isBoolean(a)&&b.set("disabled",a);return a}},serverConfig:{value:{action:"",
data:{},dataType:"json"}},action:{value:"",getter:function(){return self.get("serverConfig").action},setter:function(a){c.isString(a)&&this.set("serverConfig",c.mix(this.get("serverConfig"),{action:a}));return a}},data:{value:{},getter:function(){var a=this.get("uploadType"),b=this.get("serverConfig").data||{};a&&(b=a.get("data"));return b},setter:function(a){if(c.isObject(a)){var b=this.get("uploadType");this.set("serverConfig",c.mix(this.get("serverConfig"),{data:a}));c.isFunction(b)&&b.set("data",
a)}return a}},isAllowUpload:{value:!0},autoUpload:{value:!0},filter:{value:"",setter:function(a){var b=this.get("uploadType");b&&b.set("filter",a);return a}},urlsInputName:{value:""},curUploadIndex:{value:""},uploadType:{value:{}},urlsInput:{value:""},uploadFilesStatus:{value:""},swfSize:{value:{}}}});c.convertByteSize=function(a){var b=-1;do a/=1024,b++;while(99<a);return Math.max(a,0.1).toFixed(1)+"kB,MB,GB,TB,PB,EB".split(",")[b]};return i},{requires:"base,node,./urlsInput,./type/iframe,./type/ajax,./type/flash,./button/base,./button/swfButton,./queue".split(",")});
KISSY.add("gallery/form/1.3/uploader/button/base",function(c,j,h){function f(a,b){b=c.merge({target:d(a)},b);f.superclass.constructor.call(this,b)}var d=j.all;c.mix(f,{event:{beforeShow:"beforeShow",afterShow:"afterShow",beforeHide:"beforeHide",afterHide:"afterHide",beforeRender:"beforeRender",afterRender:"afterRender",CHANGE:"change"},getFileName:function(a){return a.replace(/.*(\/|\\)/,"")}});c.extend(f,h,{render:function(){var a=this.get("target");if(!1===this.fire(f.event.beforeRender))return c.log("[Uploader-Button] button render was prevented."),
!1;if(null==a)return c.log("[Uploader-Button] Cannot find target!"),!1;this._createInput();this.fire(f.event.afterRender);return this},show:function(){this.get("target").show();this.fire(f.event.afterShow);return f},hide:function(){this.get("target").hide();this.fire(f.event.afterHide);return f},reset:function(){var a=this.get("inputContainer");d(a).remove();this.set("inputContainer","");this.set("fileInput","");this._createInput();return this},_createInput:function(){var a=this.get("target"),b=this.get("name"),
e=this.get("tpl");if(!c.isString(b)||!c.isString(e))return c.log("[Uploader-Button] No name or tpl specified."),!1;b=c.substitute(e,{name:b});b=d(b);d(b).appendTo(a);a=d(b).children("input");6==c.UA.ie&&a.css("fontSize","400px");d(a).on("change",this._changeHandler,this);this.set("fileInput",a);this.set("inputContainer",b);this._setDisabled(this.get("disabled"));this._setMultiple(this.get("multiple"));return b},_changeHandler:function(a){var b=this.get("fileInput"),e=d(b).val(),a=a.target.files,g=
[];if(""==e)return c.log("[Uploader-Button] No file selected."),!1;a?c.each(a,function(a){c.isObject(a)&&g.push({name:a.name,type:a.type,size:a.size,data:a})}):g.push({name:f.getFileName(e)});this.fire(f.event.CHANGE,{files:g,input:b.getDOMNode()});this.reset()},_setDisabled:function(a){var b=this.get("cls").disabled,e=this.get("target"),g=this.get("fileInput");if(!e.length||!c.isBoolean(a))return!1;a?(e.addClass(b),d(g).hide()):(e.removeClass(b),d(g).show());return a},_setMultiple:function(a){var b=
this.get("fileInput");if(!b.length)return!1;a&&b.attr("multiple","multiple")||b.removeAttr("multiple");return a}},{ATTRS:{target:{value:null},fileInput:{value:""},inputContainer:{value:""},tpl:{value:'<div class="file-input-wrapper" style="overflow: hidden;"><input type="file" name="{name}" hidefocus="true" class="file-input" /></div>'},name:{value:"fileInput",setter:function(a){this.get("fileInput")&&d(this.get("fileInput")).attr("name",a);return a}},disabled:{value:!1,setter:function(a){this._setDisabled(a);
return a}},multiple:{value:!0,setter:function(a){this._setMultiple(a);return a}},cls:{value:{disabled:"uploader-button-disabled"}}}});return f},{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/button/swfButton",function(c,j,h,f){function d(b,e){e=c.merge({target:a(b)},e);d.superclass.constructor.call(this,e)}var a=j.all;c.mix(d,{event:{RENDER:"render",CHANGE:"change",MOUSE_OVER:"mouseOver",MOUSE_DOWN:"mouseDown",MOUSE_UP:"mouseUp",MOUSE_OUT:"mouseOut",CLICK:"click"}});c.extend(d,h,{render:function(){var a=this,c=a.get("target"),g,k=a.get("multiple"),i=a.get("fileFilters");c.css("position","relative");a.set("swfWrapper",a._createSwfWrapper());a._setFlashSizeConfig();
g=a._initSwfUploader();g.on("contentReady",function(){g.browse(k,i);a._bindBtnEvent();g.on("fileSelect",a._changeHandler,a);a._setDisabled(a.get("disabled"));a.fire(d.event.RENDER)},a)},_createSwfWrapper:function(){var b=this.get("target"),e=this.get("tpl"),g=""!=this.get("swfWrapperId")&&this.get("swfWrapperId")||"swf-uploader-wrapper-"+c.guid(),e=c.substitute(e,{id:g});this.set("swfWrapperId",g);return a(e).appendTo(b)},_initSwfUploader:function(){var a=this.get("flash"),e=this.get("swfWrapperId"),
g;c.mix(a,{id:"swfUploader"+c.guid()});try{g=new f(e,a),this.set("swfUploader",g)}catch(d){}return g},_bindBtnEvent:function(){var a=this,e=d.event,g=a.get("swfUploader");if(!g)return!1;c.each(e,function(c){g.on(c,function(){a.fire(c)},a)});return a},_setFlashSizeConfig:function(){var a=this.get("flash"),e=this.get("target"),g=this.get("size");c.isEmptyObject(g)?c.mix(a.attrs,{width:e.innerWidth(),height:e.innerHeight()}):c.mix(a.attrs,g);this.set("flash",a)},_changeHandler:function(a){this.fire(d.event.CHANGE,
{files:a.fileList})},_setDisabled:function(a){var e=this.get("swfUploader"),g=this.get("cls").disabled,d=this.get("target"),i=this.get("swfWrapper");if(!e||!c.isBoolean(a))return!1;a?(d.addClass(g),i.css("top","-3000px")):(d.removeClass(g),i.css("top",0));return a},show:function(){this.get("target").show()},hide:function(){this.get("target").hide()}},{ATTRS:{target:{value:""},swfWrapper:{value:""},swfWrapperId:{value:""},tpl:{value:'<div id="{id}" class="uploader-button-swf" style="position: absolute;top:0;left:0;z-index:2000;"></div>'},
multiple:{value:!0,setter:function(a){var c=this.get("swfUploader");c&&c.multifile(a);return a}},fileFilters:{value:[],setter:function(a){var e=this.get("swfUploader");c.isObject(a)&&(a=[a]);e&&c.isArray(a)&&c.later(function(){e.filter(a)},800);return a}},disabled:{value:!1,setter:function(a){this.get("swfUploader")&&this._setDisabled(a);return a}},cls:{value:{disabled:"uploader-button-disabled"}},size:{value:{}},flash:{value:{src:"http://a.tbcdn.cn/s/kissy/gallery/form/1.3/uploader/plugins/ajbridge/uploader.swf",
id:"swfUploader",params:{bgcolor:"#fff",wmode:"transparent"},attrs:{},hand:!0,btn:!0}},swfUploader:{value:""}}});return d},{requires:["node","base","../plugins/ajbridge/uploader"]});
KISSY.add("gallery/form/1.3/uploader/imageUploader",function(c,j,h,f,d){function a(a){a=a.replace(/'/g,'"');try{eval("cfg="+a)}catch(b){c.log("data-valid json is invalid")}return a}function b(a,e,d){d=c.mix(c.form.parseConfig(a),d);b.superclass.constructor.call(this,d);this.set("buttonTarget",a);this.set("queueTarget",e);this.set("uploaderConfig",d)}var e=h.all;c.mix(b,{events:"select,start,progress,complete,success,uploadFiles,cancel,error,restore".split(","),queueEvents:["add","remove","statusChange",
"clear"]});c.extend(b,f,{_init:function(){},render:function(){var a=this,b=e(a.get("buttonTarget"));if(!b.length)return!1;b.attr("theme")&&a.set("theme",b.attr("theme"));var b=a.get("theme"),d;a._setQueueTarget();a._setConfig();a._replaceBtn();""==b?(d=a._initUploader(),a.set("button",d.get("button")),c.later(function(){a.fire("render",{uploader:d,button:d.get("button"),queue:d.get("queue"),auth:d.get("auth")})},500)):a._initThemes(function(b){d=a._initUploader();a.set("button",d.get("button"));b.set("uploader",
d);b.set("button",d.get("button"));b.set("queue",d.get("queue"));b.set("auth",d.get("auth"));b._UploaderRender(function(){b.afterUploaderRender(d);a._bindEvents(d);d.restore();a.fire("render",{uploader:d,button:d.get("button"),queue:d.get("queue"),auth:d.get("auth")})})});return a},_setQueueTarget:function(){var a=this.get("queueTarget"),b=e(this.get("buttonTarget"));if(!a||!a.length)a=b.attr("queueTarget"),""!=a&&this.set("queueTarget",e(a))},_bindEvents:function(a){if(!a)return!1;var e=this,d=b.events,
f=b.queueEvents,h=a.get("queue"),j={uploader:a,queue:h};c.each(d,function(b){a.on(b,function(a){e.fire(b,c.mix(a,j))})});c.each(f,function(a){h.on(a,function(b){e.fire(a,c.mix(b,j))})})},_auth:function(){var a=this.get("uploader"),b=this.get("authConfig");if(c.isEmptyObject(b))return!1;b=new d(a,{rules:b});a.set("auth",b);return b},_setConfig:function(){var a=e(this.get("buttonTarget")),b=this.get("uploaderConfig"),d={},f=this._getAuthConfig();this.set("authConfig",f);c.isEmptyObject(f)||this.set("authConfig",
c.mix(f,this.get("authConfig")));var h={};c.each("name,urlsInputName,autoUpload,postData,action,multiple,multipleLen,uploadType,disabled".split(","),function(b){var e=a.attr(b);if(e){switch(b){case "postData":b="data";e=e&&c.JSON.parse(e);h.data=e;break;case "action":h.action=e;break;case "uploadType":b="type"}if(b=="autoUpload"||b=="multiple"||b=="disabled")e=true;d[b]=e}});d.serverConfig=h;b=c.merge(d,b);this.set("uploaderConfig",b);this.set("name",b.name)},_getAuthConfig:function(){var b=this,
d=e(b.get("buttonTarget"));if(!d.length)return!1;var f={},h=b.get("defaultAllowExts"),j=b.get("authMsg"),m=b.get("uploaderConfig"),o=d.attr("data-valid");o&&c.mix(j,a(o));c.each(["required","max","allowExts","maxSize","allowRepeat"],function(a){if(m[a])f[a]=[m[a],j[a]||""];else{var c=d.attr(a);if(c){switch(a){case "allowExts":c=b._setAllowExts(c);break;case "max":c=Number(c);break;case "maxSize":c=Number(c);break;case "required":c=!0;break;case "allowRepeat":c=!0}f[a]=[c,j[a]||""]}}});f.allowExts||
(f.allowExts=[b._setAllowExts(h),j.allowExts||""]);f.allowRepeat||(f.allowRepeat=[!1,j.allowRepeat||""]);return f},_setAllowExts:function(a){if(!c.isString(a))return a;var b=[],e=[],a=a.split(",");c.each(a,function(a){b.push("*."+a);e.push(a.toUpperCase())});b=b.join(";");e=e.join(",");return{desc:e,ext:b}},_replaceBtn:function(){var a=e(this.get("buttonTarget"));if(!a.length)return!1;var b=a.val()||"\u4e0a\u4f20\u56fe\u7247",b=c.substitute(this.get("btnTpl"),{text:b}),b=e(b).insertAfter(a);a.remove();this.set("buttonTarget",
b);this.set("uploaderConfig",c.mix(this.get("uploaderConfig"),{target:b}));return b}},{ATTRS:{theme:{value:"imageUploader"},defaultAllowExts:{value:"jpg,jpeg,png,gif,bmp"},authMsg:{value:{max:"\u6bcf\u6b21\u6700\u591a\u4e0a\u4f20{max}\u4e2a\u56fe\u7247\uff01",maxSize:"\u56fe\u7247\u5927\u5c0f\u4e3a{size}\uff0c\u8d85\u8fc7{maxSize}\uff01",required:"\u81f3\u5c11\u4e0a\u4f20\u4e00\u5f20\u56fe\u7247\uff01",require:"\u81f3\u5c11\u4e0a\u4f20\u4e00\u5f20\u56fe\u7247\uff01",allowExts:"\u4e0d\u652f\u6301{ext}\u683c\u5f0f\uff01",allowRepeat:"\u8be5\u56fe\u7247\u5df2\u7ecf\u5b58\u5728\uff01"}},btnTpl:{value:'<a href="javascript:void(0)" class="g-u ks-uploader-button"><span class="btn-text">{text}</span></a>'}}});return b},{requires:["base","node","./index",
"./auth/base"]});
KISSY.add("gallery/form/1.3/uploader/index",function(c,j,h,f,d){function a(b,e,d){d=c.mix(c.form.parseConfig(b),d);a.superclass.constructor.call(this,d);this.set("buttonTarget",b);this.set("queueTarget",e);this.set("uploaderConfig",d);this._init()}var b=h.all,e="default,imageUploader,ershouUploader,loveUploader,uploadify,refundUploader,daogouUploader,singleImageUploader".split(",");c.namespace("form");c.form.parseConfig=function(a,e){var d={},f,h=e||"data-config";f=b(a).attr(h);if(!c.isString(f))return{};try{d=
c.JSON.parse(f)}catch(j){c.log("[uploaderRender]:\u8bf7\u68c0\u67e5"+a+"\u4e0a"+h+"\u5c5e\u6027\u5185\u7684json\u683c\u5f0f\u662f\u5426\u7b26\u5408\u89c4\u8303\uff01")}return d};c.extend(a,j,{_init:function(){var a=this,b;""==a.get("theme")?(b=a._initUploader(),a.set("button",b.get("button")),c.later(function(){a.fire("init",{uploader:b,button:b.get("button"),queue:b.get("queue"),auth:b.get("auth")})},500)):a._initThemes(function(c){b=a._initUploader();a.set("button",b.get("button"));c.set("uploader",b);c.set("button",b.get("button"));c.set("queue",b.get("queue"));c.set("auth",b.get("auth"));
c._UploaderRender(function(){c.afterUploaderRender(b);b.restore();a.fire("init",{uploader:b,button:b.get("button"),queue:b.get("queue"),auth:b.get("auth")})})})},_initUploader:function(){var a=this.get("uploaderConfig");c.mix(a,{target:this.get("buttonTarget")});a=new f(a);a.render();this.set("uploader",a);this._auth();return a},_initThemes:function(a){var b=this,e=b.get("theme"),d=b.get("buttonTarget"),f=b.get("themeConfig"),h=c.form.parseConfig(d,"data-theme-config");c.mix(h,f);b.set("themeConfig",
h);e=b._getThemeName(e);c.use(e,function(c,e){var d=b.get("queueTarget"),f;c.mix(h,{queueTarget:d,buttonTarget:b.get("buttonTarget")});f=new e(h);f.on("render",function(){a&&a.call(b,f)});f.render()})},_getThemeName:function(a){var b=a;c.each(e,function(c){c==a&&(b="gallery/form/1.3/uploader/themes/"+a)});return b+="/index"},_auth:function(){var a=this.get("buttonTarget"),b=this.get("uploader"),e=this.get("authConfig"),a=c.form.parseConfig(a,"data-auth");c.mix(a,e);this.set("authConfig",a);if(c.isEmptyObject(a))return!1;
auth=new d(b,{rules:a});b.set("auth",auth);return auth}},{ATTRS:{theme:{value:"default"},themeConfig:{value:{}},buttonTarget:{value:""},queueTarget:{value:""},uploaderConfig:{},authConfig:{value:{}},button:{value:""},queue:{value:""},uploader:{value:""}}});return a},{requires:["base","node","./base","./auth/base"]});
KISSY.add("gallery/form/1.3/uploader/plugins/ajbridge/ajbridge",function(c,j){function h(e,g,k){var e=e.replace(f,""),g=j._normalize(g||{}),i=this,e=f+e,l=function(a){1>a.status?i.fire("failed",{data:a}):(c.mix(i,a),(!a.dynamic||!g.src)&&i.activate())};g.id=g.id||c.guid(d);h.instances[g.id]=i;g.src&&(g.params.allowscriptaccess="always",g.params.flashvars=c.merge(g.params.flashvars,{jsEntry:b,swfID:g.id}));k?i.__args=[e,g,l]:c.later(j.add,a,!1,j,[e,g,l])}var f="#",d="ks-ajb-",a=100,b="KISSY.AJBridge.eventHandler";
c.mix(h,{version:"1.0.15",instances:{},eventHandler:function(a,b){var c=h.instances[a];c&&c.__eventHandler(a,b)},augment:function(a,b){c.isString(b)&&(b=[b]);c.isArray(b)&&c.each(b,function(b){a.prototype[b]=function(){try{return this.callSWF(b,c.makeArray(arguments))}catch(a){this.fire("error",{message:a})}}})}});c.augment(h,c.EventTarget,{init:function(){this.__args&&(j.add.apply(j,this.__args),this.__args=null,delete this.__args)},__eventHandler:function(a,b){var d=b.type;b.id=a;switch(d){case "log":c.log(b.message);
break;default:this.fire(d,b)}},callSWF:function(a,b){b=b||[];try{if(this.swf[a])return this.swf[a].apply(this.swf,b)}catch(c){var d="";0!==b.length&&(d="'"+b.join("','")+"'");return(new Function("self","return self.swf."+a+"("+d+");"))(this)}}});h.augment(h,["activate","getReady","getCoreVersion"]);return window.AJBridge=c.AJBridge=h},{requires:["flash"]});
KISSY.add("gallery/form/1.3/uploader/plugins/ajbridge/uploader",function(c,j,h){function f(d,a){var a=a||{},b={};c.each(["ds","dsp","btn","hand"],function(c){c in a&&(b[c]=a[c])});a.params=a.params||{};a.params.flashvars=c.merge(a.params.flashvars,b);f.superclass.constructor.call(this,d,a)}c.extend(f,h);h.augment(f,"setFileFilters,filter,setAllowMultipleFiles,multifile,browse,upload,uploadAll,cancel,getFile,removeFile,lock,unlock,setBtnMode,useHand,clear".split(","));f.version="1.0.1";h.Uploader=
f;return h.Uploader},{requires:["flash","./ajbridge"]});KISSY.add("gallery/form/1.3/uploader/plugins/coverPic/coverPic",function(c,j,h){function f(){}c.extend(f,h,{render:function(){}},{ATTRS:{}});return f},{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/plugins/filedrop/filedrop",function(c,j,h){var f=j.all,d=c.UA,a=function(c){a.superclass.constructor.call(this,c);this.set("mode",b())},b=function(){if(7<=d.webkit||3.6<=d.firefox)return"supportDrop";if(d.ie)return"notSupportDropIe";if(7>d.webkit||3.6>d.firefox)return"notSupportDrop"};c.mix(a,{event:{AFTER_DROP:"afterdrop"}});c.extend(a,h,{render:function(){var a=this,b=a.get("mode"),d=a.get("uploader");if("flash"==d.get("type"))return c.log("flash\u4e0a\u4f20\u65b9\u5f0f\u4e0d\u652f\u6301\u62d6\u62fd\uff01"),
a.set("isSupport",!1),!1;if("supportDrop"!=b)return c.log("\u8be5\u6d4f\u89c8\u5668\u4e0d\u652f\u6301\u62d6\u62fd\u4e0a\u4f20\uff01"),a.set("isSupport",!1),!1;if(!d)return c.log("\u7f3a\u5c11Uploader\u7684\u5b9e\u4f8b\uff01"),!1;b=a._createDropArea();if(b.length)b.on("click",a._clickHandler,a);d.on("afterDisabledChange",function(b){a[b.newVal&&"hide"||"show"]()});a.fire("afterRender",{buttonTarget:a.get("buttonWrap")})},show:function(){this.get("dropContainer").show()},hide:function(){this.get("dropContainer").hide()},reset:function(){},_createDropArea:function(){var a=this,b=f(a.get("target")),
d=a.get("mode"),d=c.substitute(a.get("tpl")[d],{name:a.get("name")}),d=f(d),i=d.all(".J_ButtonWrap");d.appendTo(b);d.on("dragover",function(a){a.stopPropagation();a.preventDefault()});d.on("drop",function(b){b.stopPropagation();b.preventDefault();a._dropHandler(b)});a.set("dropContainer",d);a.set("buttonWrap",i);a._setStyle();return d},_setStyle:function(){var a=this.get("dropContainer");if(!a.length)return!1;a.parent().css("position","relative");a.css({position:"absolute",top:"0",left:"0",width:"100%",
height:"100%",zIndex:"1000"})},_clickHandler:function(a){f(a.target);this.get("uploader").get("button").get("fileInput").fire("click")},_dropHandler:function(b){var d=a.event,b=b.originalEvent.dataTransfer.files,f=[],i=this.get("uploader");if(!b.length||""==i)return!1;c.each(b,function(a){c.isObject(a)&&f.push({name:a.name,type:a.type,size:a.size,data:a})});this.fire(d.AFTER_DROP,{files:f});i._select({files:f})},_setDisabled:function(){}},{ATTRS:{target:{value:""},uploader:{value:""},dropContainer:{value:""},
isSupport:{value:!0},tpl:{value:{supportDrop:'<div class="drop-wrapper"><p>\u76f4\u63a5\u62d6\u62fd\u56fe\u7247\u5230\u8fd9\u91cc\uff0c</p><p class="J_ButtonWrap">\u6216\u8005</p></div>',notSupportDropIe:'<div class="drop-wrapper"><p>\u60a8\u7684\u6d4f\u89c8\u5668\u53ea\u652f\u6301\u4f20\u7edf\u7684\u56fe\u7247\u4e0a\u4f20\uff0c</p><p class="suggest J_ButtonWrap">\u63a8\u8350\u4f7f\u7528chrome\u6d4f\u89c8\u5668\u6216firefox\u6d4f\u89c8\u5668</p></div>',notSupportDrop:'<div class="drop-wrapper"><p>\u60a8\u7684\u6d4f\u89c8\u5668\u53ea\u652f\u6301\u4f20\u7edf\u7684\u56fe\u7247\u4e0a\u4f20\uff0c</p><p class="suggest J_ButtonWrap">\u63a8\u8350\u5347\u7ea7\u60a8\u7684\u6d4f\u89c8\u5668</p></div>'}},name:{value:"",setter:function(){}},disabled:{value:!1,setter:function(a){this._setDisabled(a);return a}},cls:{disabled:"drop-area-disabled"}}});
return a},{requires:["node","base"]});
KISSY.add("'gallery/form/1.3/uploader/plugins/imagePreview/imagePreview'",function(c){function j(){var f="filename";window.URL&&window.URL.createObjectURL||window.webkitURL&&window.webkitURL.createObjectURL||window.FileReader?f="html5":7===c.UA.ie||8===c.UA.ie?f="filter":6===c.UA.ie&&(f="default");return f}var h;!function(){var f={};h={add:function(d,a){f[d]?c.mix(f[d],a):f[d]=a;f[d].type=d},use:function(d){return c.mix(f["default"],f[d])}}}();h.add("default",{getData:function(c){return[c.value]},
show:function(c,d){var a=this,b=new Image;b.src=c;document.all?(b.onreadystatechange=function(){if("loaded"==b.readyState||"complete"==b.readyState)d(b,a.type),b.onreadystatechange=null},b.onreadystatechange()):b.onload=function(){d(b,a.type);b.onload=null}}});h.add("html5",{getData:function(c){for(var d=[],a=0;a<c.files.length;a++)0<=c.files[a].type.indexOf("image")&&d.push(c.files[a]);return d},show:function(c,d){var a=new Image;if(window.URL&&window.URL.createObjectURL)a.src=window.URL.createObjectURL(c);
else if(window.webkitURL&&window.webkitURL.createObjectURL)a.src=window.webkitURL.createObjectURL(c);else{var b=new FileReader;b.onload=function(b){a.src=b.target.result};b.readAsDataURL(c)}d(a,this.type)}});h.add("filter",{getData:function(c){c.select();try{return[document.selection.createRange().text]}finally{document.selection.empty()}return[]},show:function(f,d){var a=6==c.UA.ie||7==c.UA.ie?"http://img04.taobaocdn.com/tps/i4/T1Ao_pXfVpXXc6Yc2r-1-1.gif":"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";
if(!this._preload){var b=this._preload=document.createElement("div");c.DOM.css(b,{width:"1px",height:"1px",visibility:"hidden",position:"absolute",left:"-9999px",top:"-9999px",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='image')"});var e=document.body;e.insertBefore(b,e.childNodes[0])}var e=new Image,b=this._preload,g=f.replace(/[)'"%]/g,function(a){return escape(escape(a))});try{b.filters.item("DXImageTransform.Microsoft.AlphaImageLoader").src=g}catch(h){return}e.style.filter=
"progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='scale',src=\""+g+'")';e.style.width=b.offsetWidth;e.style.height=b.offsetHeight;e.src=a;e.width=b.offsetWidth;e.height=b.offsetHeight;d(e,this.type,b.offsetWidth,b.offsetHeight)}});h.add("filename",{getData:function(c){var d=[];if(c.files)for(var a=0;a<c.files.length;a++)d.push(c.files[a].name);else d.push(c.value);return d},show:function(f,d){d(c.DOM.create(f),this.type)}});return function(c,d){for(var a=h.use(j(c)),b=a.getData(c),
e=0;e<b.length;e++)a.show(b[e],d)}});
KISSY.add("gallery/form/1.3/uploader/plugins/preview/preview",function(c,j){function h(a,c){if(!a)return!1;"filter"!=b?a.src=c||e:(a.src=e,c&&(c=c.replace(/[)'"%]/g,function(a){return escape(escape(a))}),a.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='scale',src='"+c+"')",a.zoom=1));return!0}function f(d){this.config=c.mix({maxWidth:40,maxHeight:40},d);c.log(a+"Preview initialized. The preview mode is "+b)}var d=document,a="[Plugin: Preview] ",b=function(){var a="";
if("undefined"===typeof window.FileReader)switch(c.UA.shell){case "firefox":a="domfile";break;case "ie":switch(c.UA.ie){case 6:a="simple";break;default:a="filter"}}else a="html5";return a}(),e=8>c.UA.ie?"http://a.tbcdn.cn/p/fp/2011a/assets/space.gif":"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";c.augment(f,c.EventTarget,{show:function(d,e){if("html5"!=b||!e||!e.length)return!1;var f=this,h=new FileReader;h.onload=function(a){a=f.data=a.target.result;f.fire(void 0,
{data:a,mode:b});e.attr("src",a);f.fire("showed",{img:a})};h.onerror=function(){c.log(a+"File Reader Error. Your browser may not fully support html5 file api","warning");f.fire("error")};h.readAsDataURL(d)},preview:function(e,f){var e=j.get(e),f=j.get(f),i=this,l=function(){i.fire(void 0,{data:i.data,mode:b});f&&(h(f,i.data),i.fire("showed",{img:f}))};i.data=void 0;if(e){c.log(a+"One file selected. Getting data...");switch(b){case "domfile":i.data=e.files[0].getAsDataURL();break;case "filter":e.select();
try{i.data=d.selection.createRange().text}catch(n){c.log(a+"Get image data error, the error is: "),c.log(n,"dir")}finally{d.selection.empty()}i.data||(i.data=e.value);break;case "html5":var m=new FileReader;m.onload=function(a){i.data=a.target.result;l()};m.onerror=function(){c.log(a+"File Reader Error. Your browser may not fully support html5 file api","warning");i.fire("error")};e.files&&m.readAsDataURL(e.files[0]);break;default:i.data=e.value}i.data?l():"html5"!=b&&(c.log(a+"Retrive Data error."),
h(f),i.fire("error"))}else c.log(a+"File Input Element does not exists.");return i.data}});return f},{requires:["dom","event"]});
KISSY.add("gallery/form/1.3/uploader/plugins/progressBar/progressBar",function(c,j,h){function f(a,b){b=c.merge({wrapper:d(a)},b);f.superclass.constructor.call(this,b)}var d=j.all;c.mix(f,{tpl:{DEFAULT:'<div class="ks-progress-bar-value" data-value="{value}"></div>'},cls:{PROGRESS_BAR:"ks-progress-bar",VALUE:"ks-progress-bar-value"},event:{RENDER:"render",CHANGE:"change",SHOW:"show",HIDE:"hide"}});c.extend(f,h,{render:function(){var a=this.get("wrapper"),b=this.get("width");if(!a.length)return!1;
a.addClass(f.cls.PROGRESS_BAR).width(b);this._addAttr();!this.get("visible")&&this.hide();this.set("bar",this._create());this.fire(f.event.RENDER)},show:function(){var a=this;a.get("wrapper").fadeIn(a.get("duration"),function(){a.set("visible",!0);a.fire(f.event.SHOW,{visible:!0})})},hide:function(){var a=this;a.get("wrapper").fadeOut(a.get("duration"),function(){a.set("visible",!1);a.fire(f.event.HIDE,{visible:!1})})},_create:function(){var a=this.get("wrapper"),b=this.get("value"),e=this.get("tpl"),
b=c.substitute(e,{value:b});a.html("");return d(b).appendTo(a)},_addAttr:function(){var a=this.get("wrapper"),b=this.get("value");a.attr("role","progressbar");a.attr("aria-valuemin",0);a.attr("aria-valuemax",100);a.attr("aria-valuenow",b);return this}},{ATTRS:{wrapper:{value:""},bar:{value:""},width:{value:"auto"},value:{value:0,setter:function(a){var b=this,c=b.get("wrapper"),d=b.get("bar"),h=b.get("speed"),i;100<a&&(a=100);0>a&&(a=0);i=c.width()*(a/100);d.animate({width:i+"px"},h,"none",function(){c.attr("aria-valuenow",
a);d.attr("data-value",a);b.fire(f.event.CHANGE,{value:a,width:i})});return a}},visible:{value:!0},duration:{value:0.3},tpl:{value:f.tpl.DEFAULT},speed:{value:0.2}}});return f},{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/queue",function(c,j,h){function f(c){f.superclass.constructor.call(this,c)}c.mix(f,{tpl:{DEFAULT:'<li id="queue-file-{id}" class="clearfix" data-name="{name}"><div class="f-l sprite file-icon"></div><div class="f-l">{name}</div><div class="f-l file-status J_FileStatus"></div></li>'},event:{ADD:"add",ADD_FILES:"addFiles",REMOVE:"remove",CLEAR:"clear",FILE_STATUS:"statusChange",UPDATE_FILE:"updateFile",RESTORE:"restore"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",
SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"},cls:{QUEUE:"ks-uploader-queue"},hook:{STATUS:".J_FileStatus"},FILE_ID_PREFIX:"file-"});c.extend(f,h,{add:function(d,a){var b=this,e={};0<d.length?(e=[],c.each(d,function(a){e.push(b._addFile(a))})):e=b._addFile(d);a&&a.call(b);return e},_addFile:function(d,a){if(!c.isObject(d))return c.log("[uploader-queue]:_addFile()\u53c2\u6570file\u4e0d\u5408\u6cd5\uff01"),!1;var b=this._setAddFileData(d),e=this.getFileIndex(b.id),g=this.get("fnAdd");c.isFunction(g)&&(b=g(e,
b));this.fire(f.event.ADD,{index:e,file:b,uploader:this.get("uploader")});a&&a.call(this,e,b);return b},remove:function(d,a){var b=this.get("files"),e;c.isString(d)&&(d=this.getFileIndex(d));e=b[d];if(!c.isObject(e))return c.log("[uploader-queue]:remove()\u4e0d\u5b58\u5728index\u4e3a"+d+"\u7684\u6587\u4ef6\u6570\u636e"),!1;b=c.filter(b,function(a,b){return b!==d});this.set("files",b);this.fire(f.event.REMOVE,{index:d,file:e});a&&a.call(this,d,e);return e},clear:function(){function c(){b=a.get("files");if(!b.length)return a.fire(f.event.CLEAR),
!1;a.remove(0,function(){c()})}var a=this,b;c()},fileStatus:function(d,a,b){if(!c.isNumber(d))return!1;var e=this.getFile(d),g=this.get("theme"),h;if(!e)return!1;h=e.status;if(!a)return h;if(h==a)return this;this.updateFile(d,{status:a});h="_"+a+"Handler";g&&c.isFunction(g[h])&&(b=c.merge({uploader:this.get("uploader"),index:d,file:e,id:e.id},b),g[h].call(g,b));this.fire(f.event.FILE_STATUS,{index:d,status:a,args:b,file:e});return this},getFile:function(d){if(!c.isNumber(d))return!1;d=this.get("files")[d];
c.isPlainObject(d)||(c.log("getFile():\u6587\u4ef6\u6570\u636e\u4e3a\u7a7a\uff01"),d={});return d},getFileIndex:function(d){var a=this.get("files"),b=-1;c.each(a,function(a,c){if(a.id==d)return b=c,!0});return b},updateFile:function(d,a){if(!c.isNumber(d))return!1;if(!c.isObject(a))return c.log("[uploader-queue]:updateFile()\u7684data\u53c2\u6570\u6709\u8bef\uff01"),!1;var b=this.get("files"),e=this.getFile(d);if(!e)return!1;c.mix(e,a);b[d]=e;this.set("files",b);this.fire(f.event.UPDATE_FILE,{index:d,file:e});return e},getIndexs:function(d){var a=this.get("files"),
b,e=[];if(!a.length)return e;c.each(a,function(a,f){c.isObject(a)&&(b=a.status,b==d&&e.push(f))});return e},getFiles:function(d){var a=this.get("files"),b=[];if(!a.length)return[];c.each(a,function(a){a&&a.status==d&&b.push(a)});return b},_setAddFileData:function(d){var a=this.get("files");if(!c.isObject(d))return c.log("[uploader-queue]:_updateFileData()\u53c2\u6570file\u4e0d\u5408\u6cd5\uff01"),!1;d.id||(d.id=c.guid(f.FILE_ID_PREFIX));d.size&&c.convertByteSize&&(d.textSize=c.convertByteSize(d.size));d.status="";a.push(d);return d}},
{ATTRS:{fnAdd:{value:""},files:{value:[]},uploader:{value:""},theme:{value:""}}});return f},{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/theme",function(c,j,h){function f(a){f.superclass.constructor.call(this,a)}var d=j.all;c.extend(f,h,{render:function(){var a=this;a._LoaderCss(function(){a._addThemeCssName();a.fire("render")})},afterUploaderRender:function(){},_getStatusWrapper:function(a){return a&&a.children(".J_FileStatus")||d("")},displayFile:function(a,b,c){var d=this,f=d.get("duration");if(!b||!b.length)return!1;b[a&&"fadeIn"||"fadeOut"](f,function(){c&&c.call(d)})},_waitingHandler:function(){},
_startHandler:function(){},_progressHandler:function(){},_successHandler:function(){},_errorHandler:function(){},_restoreHandler:function(){},_UploaderRender:function(a){this._initQueue();this._loadPlugins(a)},_addThemeCssName:function(){var a=this.get("name"),b=d(this.get("queueTarget")),c=d(this.get("buttonTarget"));if(""==a)return!1;b.length&&b.addClass(a+"-queue");c.addClass(a+"-button")},_initQueue:function(){var a=this,b=a.get("queue");b.set("fnAdd",function(b,c){return a._addCallback(b,c)});
b.set("theme",a);b.on("add",a._addFileHandler,a);b.on("remove",a._removeFileHandler,a);b.on("statusChange",function(b){a._setStatusVisibility(b)});return b},_LoaderCss:function(a){var b=this,d=b.get("cssUrl");if(""==d)return a.call(b),!1;c.use(d,function(){c.log(d+"\u52a0\u8f7d\u6210\u529f\uff01");a.call(b)})},_addCallback:function(a,b){var c=this.get("queue"),d=this._appendFileDom(b);c.updateFile(a,{target:d,statusWrapper:this._getStatusWrapper(d)});c.fileStatus(a,"waiting");this.displayFile(!0,d);this._bindTriggerEvent(a,
b);return c.getFile(a)},_removeFileHandler:function(a){this.displayFile(!1,a.file.target)},_bindTriggerEvent:function(a,b){var e=this.get("queue"),f=this.get("uploader"),h=b.id,i=d(".J_Upload_"+h),j=d(".J_Cancel_"+h),n=d(".J_Del_"+h);i.on("click",function(b){b.preventDefault();if(!c.isObject(f))return!1;f.upload(a)});j.on("click",function(b){b.preventDefault();f.cancel(a)});n.on("click",function(a){a.preventDefault();e.remove(h)})},_setStatusVisibility:function(a){var b=a.file.statusWrapper,a=a.file,
d=a.status;if(!b||!b.length)return c.log("\u72b6\u6001\u5bb9\u5668\u5c42\u4e0d\u5b58\u5728\uff01"),!1;b.children(".status").hide();b.children("."+d+"-status").show();var f=a.target;c.each("waiting,start,uploading,progress,error,success".split(","),function(a){f.removeClass(a)});f.addClass(d)},_appendFileDom:function(a){var b=this.get("fileTpl"),e=d(this.get("queueTarget"));if(!e.length)return!1;b=c.substitute(b,a);return d(b).hide().appendTo(e).data("data-file",a)},_loadPlugins:function(a){var b=this,d=b.get("plugins"),f=b.get("oPlugin"),h=
[];if(!d.length)return a&&a.call(b,f),!1;c.each(d,function(a){h.push("gallery/form/1.3/uploader/plugins/"+a+"/"+a)});c.use(h.join(","),function(){c.each(arguments,function(a,b){1<=b&&(f[d[b-1]]=a)});b.set("oPlugin",f);a&&a.call(b,f)})}},{ATTRS:{name:{value:""},cssUrl:{value:""},fileTpl:{value:""},plugins:{value:[]},oPlugin:{value:{}},queueTarget:{value:""},duration:{value:0.3},queue:{value:""},uploader:{value:""},button:{value:""},auth:{value:""}}});return f},{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/type/ajax",function(c,j,h){function f(c){f.superclass.constructor.call(this,c)}c.mix(f,{event:c.merge(h.event,{PROGRESS:"progress"})});c.extend(f,h,{upload:function(d){if(!d)return c.log("[uploader-AjaxType]:upload()\uff0cfileData\u53c2\u6570\u6709\u8bef\uff01"),!1;this._setFormData();this._addFileData(d);this.send();return this},stop:function(){var d=this.get("xhr");if(!c.isObject(d))return c.log("[uploader-AjaxType]:stop()\uff0cio\u503c\u9519\u8bef\uff01"),!1;d.abort();this.fire(f.event.STOP);return this},send:function(){var c=
this,a=c.get("action"),b=c.get("formData"),e=new XMLHttpRequest;e.upload.addEventListener("progress",function(a){c.fire(f.event.PROGRESS,{loaded:a.loaded,total:a.total})});e.onload=function(){var a=c._processResponse(e.responseText);c.fire(f.event.SUCCESS,{result:a})};e.open("POST",a,!0);b.append("type","ajax");e.send(b);c._setFormData();c.set("xhr",e);return c},_setFormData:function(){try{this.set("formData",new FormData),this._processData()}catch(d){c.log("[uploader-AjaxType]:something error when reset FormData."),
c.log(d,"dir")}},_processData:function(){var d=this.get("data"),a=this.get("formData");c.each(d,function(b,c){a.append(c,b)});this.set("formData",a)},_addFileData:function(d){if(!c.isObject(d))return c.log("[uploader-AjaxType]:_addFileData()\uff0cfile\u53c2\u6570\u6709\u8bef\uff01"),!1;var a=this.get("formData"),b=this.get("fileDataName");a.append(b,d);this.set("formData",a)}},{ATTRS:{formData:{value:""},ajaxConfig:{value:{type:"post",processData:!1,cache:!1,dataType:"json",contentType:!1}},xhr:{value:""},fileDataName:{value:""},
form:{value:{}},fileInput:{value:""}}});return f},{requires:["node","./base"]});
KISSY.add("gallery/form/1.3/uploader/type/base",function(c,j,h){function f(c){f.superclass.constructor.call(this,c)}c.mix(f,{event:{START:"start",STOP:"stop",SUCCESS:"success",ERROR:"error"}});c.extend(f,h,{upload:function(){},stop:function(){},_processResponse:function(d){var a=this.get("filter"),b={};""!=a&&(d=a.call(this,d));if(c.isString(d))try{b=c.JSON.parse(d),b=this._fromUnicode(b)}catch(e){d+="\uff0c\u8fd4\u56de\u7ed3\u679c\u96c6responseText\u683c\u5f0f\u4e0d\u5408\u6cd5\uff01",c.log(d),this.fire("error",{status:-1,result:{msg:d}})}else c.isObject(d)&&
(b=this._fromUnicode(d));c.log("\u670d\u52a1\u5668\u7aef\u8f93\u51fa\uff1a"+c.JSON.stringify(b));return b},_fromUnicode:function(d){function a(b){c.each(b,function(d,f){c.isObject(b[f])?a(b[f]):b[f]=c.isString(d)&&c.fromUnicode(d)||d})}if(!c.isObject(d))return d;a(d);return d}},{ATTRS:{action:{value:""},data:{value:{}},filter:{value:""}}});return f},{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/type/flash",function(c,j,h){function f(c){f.superclass.constructor.call(this,c);this.isHasCrossdomain();this._init()}if(c.FlashType)return c.FlashType;c.mix(f,{event:c.merge(h.event,{SWF_READY:"swfReady",PROGRESS:"progress"})});c.extend(f,h,{_init:function(){var d=this,a=d.get("swfUploader");if(!a)return c.log("[uploader-FlashType]:swfUploader\u5bf9\u8c61\u4e3a\u7a7a\uff01"),!1;a.on("contentReady",function(){d.fire(f.event.SWF_READY)},d);a.on("uploadStart",d._uploadStartHandler,d);a.on("uploadProgress",
d._uploadProgressHandler,d);a.on("uploadCompleteData",d._uploadCompleteDataHandler,d);a.on("uploadError",d._uploadErrorHandler,d)},upload:function(d){var a=this.get("swfUploader"),b=this.get("action"),e=this.get("data"),f=this.get("fileDataName");f||(f="Filedata");this.set("uploadingId",d);c.mix(e,{type:"flash"});a.upload(d,b,"POST",e,f);return this},stop:function(){var c=this.get("swfUploader"),a=this.get("uploadingId");""!=a&&(c.cancel(a),this.fire(f.event.STOP,{id:a}));return this},_uploadStartHandler:function(c){this.fire(f.event.START,
{file:c.file})},_uploadProgressHandler:function(d){c.mix(d,{loaded:d.bytesLoaded,total:d.bytesTotal});c.log("[uploader-FlashType]:\u5df2\u7ecf\u4e0a\u4f20\u5b57\u8282\u6570\u4e3a\uff1a"+d.bytesLoaded);this.fire(f.event.PROGRESS,{loaded:d.loaded,total:d.total})},_uploadCompleteDataHandler:function(c){c=this._processResponse(c.data);this.set("uploadingId","");this.fire(f.event.SUCCESS,{result:c})},_uploadErrorHandler:function(c){this.set("uploadingId","");this.fire(f.event.ERROR,{msg:c.msg})},isHasCrossdomain:function(){c.io({url:"http://"+location.hostname+
"/crossdomain.xml",dataType:"xml",error:function(){c.log("\u7f3a\u5c11crossdomain.xml\u6587\u4ef6\u6216\u8be5\u6587\u4ef6\u4e0d\u5408\u6cd5\uff01")}})}},{ATTRS:{action:{value:"",getter:function(d){if(!/^http/.test(d))var a=location.href.split("/"),d=c.filter(a,function(b,c){return c<a.length-1}).join("/")+"/"+d;return d}},swfUploader:{value:""},uploadingId:{value:""}}});return c.FlashType=f},{requires:["node","./base"]});
KISSY.add("gallery/form/1.3/uploader/type/iframe",function(c,j,h){function f(a){f.superclass.constructor.call(this,a)}var d=j.all;c.mix(f,{tpl:{IFRAME:'<iframe src="javascript:false;" name="{id}" id="{id}" border="no" width="1" height="1" style="display: none;" />',FORM:'<form method="post" enctype="multipart/form-data" action="{action}" target="{target}" style="visibility: hidden;">{hiddenInputs}</form>',HIDDEN_INPUT:'<input type="hidden" name="{name}" value="{value}" />'},event:c.mix(h.event,{CREATE:"create",
REMOVE:"remove"})});c.extend(f,h,{upload:function(a){a=d(a);if(!a.length)return!1;this.fire(f.event.START,{input:a});this.set("fileInput",a);this._create();a=this.get("form");if(!a)return c.log("[uploader-iframeType]:form\u8282\u70b9\u4e0d\u5b58\u5728\uff01"),!1;a.getDOMNode().submit()},stop:function(){this.get("iframe").attr("src",'javascript:"<html></html>";');this._remove();this.fire(f.event.STOP);this.fire(f.event.ERROR,{status:"abort",msg:"\u4e0a\u4f20\u5931\u8d25\uff0c\u539f\u56e0\uff1aabort"});return this},dataToHidden:function(a){if(!c.isObject(a)||c.isEmptyObject(a))return"";
var b="",d=this.get("tpl").HIDDEN_INPUT;if(!c.isString(d))return"";for(var f in a)b+=c.substitute(d,{name:f,value:a[f]});return b},_createIframe:function(){var a="ks-uploader-iframe-"+c.guid(),b=this.get("tpl"),e=b.IFRAME,f=this.get("iframe");if(!c.isEmptyObject(f))return f;if(!c.isString(e))return c.log("[uploader-iframeType]:iframe\u7684\u6a21\u677f\u4e0d\u5408\u6cd5\uff01"),!1;if(!c.isString(a))return c.log("[uploader-iframeType]:id\u5fc5\u987b\u5b58\u5728\u4e14\u4e3a\u5b57\u7b26\u4e32\u7c7b\u578b\uff01"),!1;b=c.substitute(b.IFRAME,{id:a});b=d(b);b.on("load",this._iframeLoadHandler,this);
d("body").append(b);this.set("id",a);this.set("iframe",b);return b},_iframeLoadHandler:function(a){var b=a.target,a=f.event.ERROR,b=b.contentDocument||window.frames[b.id].document;if(!b||!b.body)return this.fire(a,{msg:"\u670d\u52a1\u5668\u7aef\u8fd4\u56de\u6570\u636e\u6709\u95ee\u9898\uff01"}),!1;a=b.body.innerHTML;if(""==a)return!1;a=this._processResponse(a);this.fire(f.event.SUCCESS,{result:a});this._remove()},_createForm:function(){var a=this.get("id"),b=this.get("tpl").FORM,e=this.get("data"),f=this.get("action"),h=this.get("fileInput");if(!c.isString(b))return c.log("[uploader-iframeType]:form\u6a21\u677f\u4e0d\u5408\u6cd5\uff01"),
!1;if(!c.isString(f))return c.log("[uploader-iframeType]:action\u53c2\u6570\u4e0d\u5408\u6cd5\uff01"),!1;e=this.dataToHidden(e);e+=this.dataToHidden({type:"iframe"});a=c.substitute(b,{action:f,target:a,hiddenInputs:e});h=d(a).append(h);d("body").append(h);this.set("form",h);return h},_create:function(){var a=this._createIframe(),b=this._createForm();this.fire(f.event.CREATE,{iframe:a,form:b})},_remove:function(){var a=this.get("form");if(!a)return!1;a.remove();this.reset("form");this.fire(f.event.REMOVE,{form:a})}},{ATTRS:{tpl:{value:f.tpl},
id:{value:"ks-uploader-iframe-"+c.guid()},iframe:{value:{}},form:{value:""},fileInput:{value:""}}});return f},{requires:["node","./base"]});
KISSY.add("gallery/form/1.3/uploader/urlsInput",function(c,j,h){function f(a,b){f.superclass.constructor.call(this,b);this.set("wrapper",d(a))}var d=j.all;c.mix(f,{TPL:'<input type="hidden" id="{name}" name="{name}" value="{value}" />'});c.extend(f,h,{render:function(){var a=this.get("wrapper"),b=this.get("name"),b=document.getElementsByName(b)[0];if(!c.isObject(a))return c.log("[uploader-urlsInput]:container\u53c2\u6570\u4e0d\u5408\u6cd5\uff01"),!1;b?(c.log("[uploader-urlsInput]:urls input found"),this.set("input",d(b))):this._create();
return this},add:function(a){if(!c.isString(a))return c.log("[uploader-urlsInput]:add()\u7684url\u53c2\u6570\u4e0d\u5408\u6cd5\uff01"),!1;var b=this.get("urls"),d=this.isExist(a);""==b[0]&&(b=[]);if(d)return c.log("[uploader-urlsInput]:add()\uff0c\u6587\u4ef6\u8def\u5f84\u5df2\u7ecf\u5b58\u5728\uff01"),this;b.push(a);this.set("urls",b);this._val();return this},remove:function(a){if(!a)return!1;var b=this.get("urls"),d=this.isExist(a),f=RegExp(a);if(!d)return c.log("[uploader-urlsInput]:remove()\uff0c\u4e0d\u5b58\u5728\u8be5\u6587\u4ef6\u8def\u5f84\uff01"),!1;b=c.filter(b,function(a){return!f.test(a)});this.set("urls",b);this._val();
return b},parse:function(){var a=this.get("input");if(a){var a=d(a).val(),b=this.get("split");if(""==a)return[];a=a.split(b);this.set("urls",a);return a}c.log("[uploader-urlsInput]:cannot find urls input.");return[]},_val:function(){var a=this.get("urls"),b=this.get("input"),c=this.get("split"),a=a.join(c);b.val(a);return a},isExist:function(a){var b=!1,d=this.get("urls"),f=RegExp(a);if(!d.length)return!1;c.each(d,function(a){if(f.test(a))return b=!0});return b},_create:function(){var a=this.get("wrapper"),
b=this.get("tpl"),e=this.get("name"),f=this.get("urls");if(!a||0>=a.length)return c.log("[uploader-urlsInput]:UrlsInput container not specified!","warn"),!1;if(!c.isString(b)||!c.isString("name"))return c.log("[uploader-urlsInput]:_create()\uff0ctpl\u548cname\u5c5e\u6027\u4e0d\u5408\u6cd5\uff01"),!1;b=d(c.substitute(b,{name:e,value:f}));a.append(b);this.set("input",b);c.log("[uploader-urlsInput]:input created.");return b}},{ATTRS:{name:{value:""},urls:{value:[]},tpl:{value:f.TPL},split:{value:",",setter:function(a){this._val();return a}},
input:{value:""},wrapper:{value:""}}});return f},{requires:["node","base"]});
