KISSY.add("gallery/form/1.3/uploader/auth/base",function(c,j,g){function e(a,b){b=c.merge({uploader:a},b);e.superclass.constructor.call(this,b);this._init()}var d=d||c;c.mix(e,{event:{ERROR:"error"},defaultRules:{allowExts:[{desc:"JPG,JPEG,PNG,GIF,BMP",ext:"*.jpg;*.jpeg;*.png;*.gif;*.bmp"},"\u4e0d\u652f\u6301{ext}\u683c\u5f0f\u7684\u6587\u4ef6\u4e0a\u4f20\uff01"],required:[!1,"\u5fc5\u987b\u81f3\u5c11\u4e0a\u4f20\u4e00\u4e2a\u6587\u4ef6\uff01"],max:[3,"\u6bcf\u6b21\u6700\u591a\u4e0a\u4f20{max}\u4e2a\u6587\u4ef6\uff01"],maxSize:[1E3,"\u6587\u4ef6\u5927\u5c0f\u4e3a{size}\uff0c\u6587\u4ef6\u592a\u5927\uff01"],allowRepeat:[!1,"\u8be5\u6587\u4ef6\u5df2\u7ecf\u5b58\u5728\uff01"]}});c.extend(e,g,{_init:function(){var a=this,b=a.get("uploader"),c=b.get("queue");
if(""==b)return d.log("[uploader-auth]:uploader\u4e0d\u53ef\u4ee5\u4e3a\u7a7a\uff01"),!1;a._setSwfButtonExt();a._addUploaderAttrs();b.testMax=function(){return a.testMax()};b.testRequired=function(){return a.testRequired()};b.test=function(){return a.testMax()&&a.testRequired()};c.on("add",function(b){b=b.file;if("restore"!=b.type){var c=!0;(c=a.testAllowExt(b))&&(c=a.testMaxSize(b));c&&a.testRepeat(b)}});c.on("remove",function(b){"success"==b.file.status&&a.testMax()&&a.testRequired()});c.on("statusChange",function(c){c=c.status;
"start"==c&&b.get("disabled")&&a._maxStopUpload();"success"==c&&a.testMax()});b.on("error",function(){b.set("isAllowUpload",!0)})},_addUploaderAttrs:function(){var a=this,b=a.get("uploader"),f=a.get("rules");c.each(e.defaultRules,function(h,d){var e=!c.isUndefined(f[d]),k=e&&f[d][0]||null;e&&b.addAttr(d,{value:k,getter:function(b){"allowExts"==d&&(b=a.getAllowExts(b));return b},setter:function(b){var c=a.get("rules");"allowExts"==d&&(b=a.setAllowExts(b));return c[d][0]=b}})})},setAllowExts:function(a){if(!c.isString(a))return!1;
var b=[],f=[],a=a.split(",");c.each(a,function(a){b.push("*."+a);f.push(a.toUpperCase())});b=b.join(";");f=f.join(",");return{desc:f,ext:b}},getAllowExts:function(a){if(!c.isObject(a))return a;var a=a.ext.split(";"),b=[];c.each(a,function(a){b.push(a.replace("*.",""))});return b.join(",")},testAll:function(){return this.testRequire()&&this.testMax()},getRule:function(a){return this.get("rules")[a]},isUploaderType:function(a){var b=this.get("uploader").get("type");return a==b},testRequire:function(){var a=
this.get("uploader").get("urlsInput").get("urls"),b=this.getRule("required")||this.getRule("require"),a=0<a.length;if(!b||!b[0])return!0;a||(c.log("[uploader-auth]:"+b[1]),this._fireUploaderError("required",b));return a},testRequired:function(){return this.testRequire()},testAllowExt:function(a){function b(a){a=a.split(".");return a[a.length-1]}if(!c.isObject(a))return!1;var f=a.name,d=this.getRule("allowExts"),e=[],i;if(!c.isArray(d))return!1;e=this._getExts(d[0].ext);i=function(a){var b=!1,f;c.each(e,
function(c){f=RegExp("^.+."+c+"$");if(f.test(a))return b=!0});return b}(f);i||(f=b(f),f=c.substitute(d[1],{ext:f}),this._fireUploaderError("allowExts",[d[0],f],a));return i},testMax:function(){var a=this.get("uploader"),b=a.get("queue").getFiles("success").length,f=this.getRule("max");if(f){if(!f[0])return!0;(b=b<f[0])?(a.set("disabled",!1),a.set("isAllowUpload",!0)):(a.set("disabled",!0),a.set("isAllowUpload",!1),a=c.substitute(f[1],{max:f[0]}),this._fireUploaderError("max",[f[0],a]));return b}},
testMaxSize:function(a){var b=a.size,f=this.getRule("maxSize");if(f){var d=this.get("uploader");if(c.UA.ie&&"iframe"==d.get("type"))return!0;d=1024*Number(f[0]);b=b<=d;b||(d=c.substitute(f[1],{maxSize:c.convertByteSize(d),size:a.textSize}),this._fireUploaderError("maxSize",[f[0],d],a));return b}},testRepeat:function(a){if(!c.isObject(a))return!1;var b=this,f=a.name,d=b.getRule("allowRepeat");if(d){var e=d[0],i=b.get("uploader").get("queue").getFiles("success"),k=!1;if(e)return!1;c.each(i,function(c){if(c.name==
f&&c.size==a.size)return b._fireUploaderError("allowRepeat",d,a),k=!0});return k}},_setSwfButtonExt:function(){var a=this.get("uploader"),b=this.getRule("allowExts"),a=a.get("button");if(!this.isUploaderType("flash")||!c.isArray(b))return!1;a&&a.set("fileFilters",b[0]);return this},_getExts:function(a){if(!c.isString(a))return!1;var b=a.split(";"),f=[],d=/^\*\./;c.each(b,function(a){a=a.replace(d,"");f.push(a.toUpperCase())});c.each(f,function(a){b.push(a)});return b},_fireUploaderError:function(a,
b,f){var d=this.get("uploader"),l=d.get("queue"),a={status:-1,rule:a},i=-1;f&&(i=l.getFileIndex(f.id),c.mix(a,{file:f,index:i}));b&&c.mix(a,{msg:b[1],value:b[0],result:{}});l.fileStatus(i,"error",a);this.fire(e.event.ERROR,a);d.fire("error",a)},_maxStopUpload:function(){var a=this.get("uploader"),b=a.get("queue"),f=a.get("curUploadIndex");if(""==f)return!1;var d=b.get("files");a.stop();c.each(d,function(a,c){c>=f&&b.remove(c)})}},{ATTRS:{uploader:{value:""},rules:{value:e.defaultRules}}});return e},
{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/base",function(c,j,g,e,d,a,b,f,h,l){function i(a){i.superclass.constructor.call(this,a)}c.mix(i,{type:{AUTO:"auto",IFRAME:"iframe",AJAX:"ajax",FLASH:"flash"},event:{RENDER:"render",SELECT:"select",START:"start",PROGRESS:"progress",COMPLETE:"complete",SUCCESS:"success",UPLOAD_FILES:"uploadFiles",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"}});
c.extend(i,j,{render:function(){var a=this,b=a.get("serverConfig"),f=a.get("type"),d=a.getUploadType(f),f=d.event,h;if(!d)return!1;h=a._renderButton();a.set("urlsInput",a._renderUrlsInput());a._renderQueue();a.get("type")==i.type.FLASH&&c.mix(b,{swfUploader:h.get("swfUploader")});b.fileDataName=a.get("name");b=new d(b);b.on(f.SUCCESS,a._uploadCompleteHanlder,a);b.on(f.ERROR,function(b){a.fire(event.ERROR,{status:b.status,result:b.result})},a);if(f.PROGRESS)b.on(f.PROGRESS,a._uploadProgressHandler,
a);b.on(f.STOP,a._uploadStopHanlder,a);a.set("uploadType",b);a.fire(i.event.RENDER);return a},upload:function(a){if(!c.isNumber(a))return!1;var b=this.get("uploadType"),f=this.get("type"),d=this.get("queue"),h=d.get("files")[a],e;if(!c.isPlainObject(h))return c.log("[uploader]:\u961f\u5217\u4e2d\u4e0d\u5b58\u5728id\u4e3a"+a+"\u7684\u6587\u4ef6"),!1;if(""!=this.get("curUploadIndex"))return alert("\u7b2c"+this.get("curUploadIndex")+"\u6587\u4ef6\u6b63\u5728\u4e0a\u4f20\uff0c\u8bf7\u4e0a\u4f20\u5b8c\u540e\u518d\u64cd\u4f5c\uff01"),!1;e=h.input.id||h.input;"ajax"==f&&(e=h.data);if("error"===h.status)return!1;this.fire(i.event.START,
{index:a,file:h});if(!this.get("isAllowUpload"))return!1;this.set("curUploadIndex",a);d.fileStatus(a,i.status.START);b.upload(e)},cancel:function(a){var b=this.get("uploadType"),f=this.get("queue"),d=i.status,h=f.fileStatus(a);c.isNumber(a)&&h!=d.SUCCESS?(b.stop(),f.fileStatus(a,d.CANCEL)):(b.stop(),this._continueUpload());return this},stop:function(){this.set("uploadFilesStatus","");this.cancel();return this},uploadFiles:function(a){c.isString(a)||(a=i.status.WAITING);this.set("uploadFilesStatus",
a);this._uploaderStatusFile(a);return this},_uploaderStatusFile:function(a){a=this.get("queue").getIndexs(a);if(!a.length)return this.set("uploadFilesStatus",""),this.fire(i.event.UPLOAD_FILES),!1;this.upload(a[0]);return this},isSupportAjax:function(){var a=!1;try{FormData&&(a=!0)}catch(b){a=!1}return a},isSupportFlash:function(){var a=c.UA.fpv();return c.isArray(a)&&0<a.length},getUploadType:function(a){var b=this,f=i.type,d;a==f.AUTO&&(a=[f.AJAX,f.FLASH,f.IFRAME]);c.isArray(a)&&0<a.length?c.each(a,
function(a){if(d=b._getType(a))return!1}):d=b._getType(a);return d},_getType:function(f){var h=i.type,e=this.isSupportAjax(),l=this.isSupportFlash();switch(f){case h.IFRAME:h=d;break;case h.AJAX:h=e&&a||!1;break;case h.FLASH:h=l&&b||!1;break;default:return c.log("[uploader]:type\u53c2\u6570\u4e0d\u5408\u6cd5"),!1}h&&c.log("[uploader]:\u4f7f\u7528"+f+"\u4e0a\u4f20\u65b9\u5f0f");this.set("type",f);return h},_renderButton:function(){var a,b;b=this.get("type");a=this.get("target");var d=this.get("multiple"),e=this.get("disabled"),d={name:this.get("name"),
multiple:d,disabled:e};b==i.type.FLASH?(b=h,c.mix(d,{size:this.get("swfSize")})):b=f;a=new b(a,d);a.on("change",this._select,this);a.render();this.set("button",a);return a},_renderQueue:function(){var a=new l,b=this.get("urlsInput");if(!c.isObject(a))return c.log("[uploader]:queue\u53c2\u6570\u4e0d\u5408\u6cd5"),!1;a.set("uploader",this);a.on("remove",function(a){a.file.sUrl&&b&&b.remove(a.file.sUrl)});this.set("queue",a);return a},_select:function(a){var b=this,f=b.get("autoUpload"),d=b.get("queue"),h=b.get("curUploadIndex"),
e=a.files;c.each(e,function(b){b.size||(b.size=0);b.name||(b.name=b.fileName||"");b.input=a.input||b});e=b._processExceedMultiple(e);b.fire(i.event.SELECT,{files:e});if(!b.get("isAllowUpload"))return!1;d.add(e,function(){""==h&&f&&b.uploadFiles()})},_processExceedMultiple:function(a){var b=this.get("multipleLen");return 0>b||!c.isArray(a)||!a.length?a:c.filter(a,function(a,c){return c<b})},_renderUrlsInput:function(){var a=this.get("button").get("target"),b=this.get("urlsInputName"),a=new e(a,{name:b});
a.render();return a},_uploadCompleteHanlder:function(a){var a=a.result,b,f=i.event,d=this.get("queue"),h=this.get("curUploadIndex");if(!c.isObject(a))return!1;d.updateFile(h,{result:a});b=Number(a.status);1===b?(d.fileStatus(h,i.status.SUCCESS),this._success(a.data),this.fire(f.SUCCESS,{index:h,file:d.getFile(h),result:a})):(d.fileStatus(h,i.status.ERROR,{msg:a.msg||a.message||"",result:a}),this.fire(f.ERROR,{status:b,result:a,index:h,file:d.getFile(h)}));this.set("curUploadIndex","");this.fire(f.COMPLETE,
{index:h,file:d.getFile(h),result:a});this._continueUpload()},_uploadStopHanlder:function(){var a=this.get("queue"),b=this.get("curUploadIndex");a.fileStatus(b,i.status.CANCEL);this.set("curUploadIndex","");this.fire(i.event.CANCEL,{index:b})},_continueUpload:function(){var a=this.get("uploadFilesStatus");""!=a&&this._uploaderStatusFile(a)},_uploadProgressHandler:function(a){var b=this.get("queue"),f=this.get("curUploadIndex"),d=b.getFile(f);c.mix(a,{file:d});b.fileStatus(f,i.status.PROGRESS,a);this.fire(i.event.PROGRESS,
a)},_success:function(a){if(!c.isObject(a))return!1;var a=a.url,b=this.get("urlsInput"),f=this.get("curUploadIndex"),d=this.get("queue");if(!c.isString(a)||!c.isObject(b))return!1;d.updateFile(f,{sUrl:a});b.add(a)},restore:function(a){var b=this.get("queue");this.get("urlsInput");a||(a=this._getRestoreData());if(!a.length)return!1;c.each(a,function(a){var a=b.add(a),c=a.id,f=b.getFileIndex(c);b.fileStatus(f,"success",{index:f,id:c,file:a})})},_getRestoreData:function(){var a=this.get("urlsInput").parse(),
b=[];c.each(a,function(a){b.push({name:a,type:"restore",url:a,sUrl:a,result:{status:1,data:{name:a,url:a}}})});return b}},{ATTRS:{button:{value:{}},queue:{value:{}},type:{value:i.type.AUTO},multiple:{value:!0,setter:function(a){var b=this.get("button");!c.isEmptyObject(b)&&c.isBoolean(a)&&b.set("multiple",a);return a}},multipleLen:{value:-1},disabled:{value:!1,setter:function(a){var b=this.get("button");!c.isEmptyObject(b)&&c.isBoolean(a)&&b.set("disabled",a);return a}},serverConfig:{value:{action:"",
data:{},dataType:"json"}},action:{value:"",getter:function(){return self.get("serverConfig").action},setter:function(a){c.isString(a)&&this.set("serverConfig",c.mix(this.get("serverConfig"),{action:a}));return a}},data:{value:{},getter:function(){var a=this.get("uploadType"),b=this.get("serverConfig").data||{};a&&(b=a.get("data"));return b},setter:function(a){if(c.isObject(a)){var b=this.get("uploadType");this.set("serverConfig",c.mix(this.get("serverConfig"),{data:a}));c.isFunction(b)&&b.set("data",
a)}return a}},isAllowUpload:{value:!0},autoUpload:{value:!0},filter:{value:"",setter:function(a){var b=this.get("uploadType");b&&b.set("filter",a);return a}},urlsInputName:{value:""},curUploadIndex:{value:""},uploadType:{value:{}},urlsInput:{value:""},uploadFilesStatus:{value:""},swfSize:{value:{}}}});c.convertByteSize=function(a){var b=-1;do a/=1024,b++;while(99<a);return Math.max(a,0.1).toFixed(1)+"kB,MB,GB,TB,PB,EB".split(",")[b]};return i},{requires:"base,node,./urlsInput,./type/iframe,./type/ajax,./type/flash,./button/base,./button/swfButton,./queue".split(",")});
KISSY.add("gallery/form/1.3/uploader/button/base",function(c,j,g){function e(a,b){b=c.merge({target:d(a)},b);e.superclass.constructor.call(this,b)}var d=j.all;c.mix(e,{event:{beforeShow:"beforeShow",afterShow:"afterShow",beforeHide:"beforeHide",afterHide:"afterHide",beforeRender:"beforeRender",afterRender:"afterRender",CHANGE:"change"},getFileName:function(a){return a.replace(/.*(\/|\\)/,"")}});c.extend(e,g,{render:function(){var a=this.get("target");if(!1===this.fire(e.event.beforeRender))return c.log("[Uploader-Button] button render was prevented."),
!1;if(null==a)return c.log("[Uploader-Button] Cannot find target!"),!1;this._createInput();this.fire(e.event.afterRender);return this},show:function(){this.get("target").show();this.fire(e.event.afterShow);return e},hide:function(){this.get("target").hide();this.fire(e.event.afterHide);return e},reset:function(){var a=this.get("inputContainer");d(a).remove();this.set("inputContainer","");this.set("fileInput","");this._createInput();return this},_createInput:function(){var a=this.get("target"),b=this.get("name"),
f=this.get("tpl");if(!c.isString(b)||!c.isString(f))return c.log("[Uploader-Button] No name or tpl specified."),!1;b=c.substitute(f,{name:b});b=d(b);d(b).appendTo(a);a=d(b).children("input");6==c.UA.ie&&a.css("fontSize","400px");d(a).on("change",this._changeHandler,this);this.set("fileInput",a);this.set("inputContainer",b);this._setDisabled(this.get("disabled"));this._setMultiple(this.get("multiple"));return b},_changeHandler:function(a){var b=this.get("fileInput"),f=d(b).val(),a=a.target.files,h=
[];if(""==f)return c.log("[Uploader-Button] No file selected."),!1;a?c.each(a,function(a){c.isObject(a)&&h.push({name:a.name,type:a.type,size:a.size,data:a})}):h.push({name:e.getFileName(f)});this.fire(e.event.CHANGE,{files:h,input:b.getDOMNode()});this.reset()},_setDisabled:function(a){var b=this.get("cls").disabled,f=this.get("target"),h=this.get("fileInput");if(!f.length||!c.isBoolean(a))return!1;a?(f.addClass(b),d(h).hide()):(f.removeClass(b),d(h).show());return a},_setMultiple:function(a){var b=
this.get("fileInput");if(!b.length)return!1;a&&b.attr("multiple","multiple")||b.removeAttr("multiple");return a}},{ATTRS:{target:{value:null},fileInput:{value:""},inputContainer:{value:""},tpl:{value:'<div class="file-input-wrapper" style="overflow: hidden;"><input type="file" name="{name}" hidefocus="true" class="file-input" /></div>'},name:{value:"fileInput",setter:function(a){this.get("fileInput")&&d(this.get("fileInput")).attr("name",a);return a}},disabled:{value:!1,setter:function(a){this._setDisabled(a);
return a}},multiple:{value:!0,setter:function(a){this._setMultiple(a);return a}},cls:{value:{disabled:"uploader-button-disabled"}}}});return e},{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/button/swfButton",function(c,j,g,e){function d(b,f){f=c.merge({target:a(b)},f);d.superclass.constructor.call(this,f)}var a=j.all;c.mix(d,{event:{RENDER:"render",CHANGE:"change",MOUSE_OVER:"mouseOver",MOUSE_DOWN:"mouseDown",MOUSE_UP:"mouseUp",MOUSE_OUT:"mouseOut",CLICK:"click"}});c.extend(d,g,{render:function(){var a=this,c=a.get("target"),h,e=a.get("multiple"),i=a.get("fileFilters");c.css("position","relative");a.set("swfWrapper",a._createSwfWrapper());a._setFlashSizeConfig();
h=a._initSwfUploader();h.on("contentReady",function(){h.browse(e,i);a._bindBtnEvent();h.on("fileSelect",a._changeHandler,a);a._setDisabled(a.get("disabled"));a.fire(d.event.RENDER)},a)},_createSwfWrapper:function(){var b=this.get("target"),f=this.get("tpl"),d=""!=this.get("swfWrapperId")&&this.get("swfWrapperId")||"swf-uploader-wrapper-"+c.guid(),f=c.substitute(f,{id:d});this.set("swfWrapperId",d);return a(f).appendTo(b)},_initSwfUploader:function(){var a=this.get("flash"),f=this.get("swfWrapperId"),
d;c.mix(a,{id:"swfUploader"+c.guid()});try{d=new e(f,a),this.set("swfUploader",d)}catch(l){}return d},_bindBtnEvent:function(){var a=this,f=d.event,h=a.get("swfUploader");if(!h)return!1;c.each(f,function(c){h.on(c,function(){a.fire(c)},a)});return a},_setFlashSizeConfig:function(){var a=this.get("flash"),f=this.get("target"),d=this.get("size");c.isEmptyObject(d)?c.mix(a.attrs,{width:f.innerWidth(),height:f.innerHeight()}):c.mix(a.attrs,d);this.set("flash",a)},_changeHandler:function(a){this.fire(d.event.CHANGE,
{files:a.fileList})},_setDisabled:function(a){var f=this.get("swfUploader"),d=this.get("cls").disabled,e=this.get("target"),i=this.get("swfWrapper");if(!f||!c.isBoolean(a))return!1;a?(e.addClass(d),i.css("top","-3000px")):(e.removeClass(d),i.css("top",0));return a},show:function(){this.get("target").show()},hide:function(){this.get("target").hide()}},{ATTRS:{target:{value:""},swfWrapper:{value:""},swfWrapperId:{value:""},tpl:{value:'<div id="{id}" class="uploader-button-swf" style="position: absolute;top:0;left:0;z-index:2000;"></div>'},
multiple:{value:!0,setter:function(a){var c=this.get("swfUploader");c&&c.multifile(a);return a}},fileFilters:{value:[],setter:function(a){var f=this.get("swfUploader");c.isObject(a)&&(a=[a]);f&&c.isArray(a)&&c.later(function(){f.filter(a)},800);return a}},disabled:{value:!1,setter:function(a){this.get("swfUploader")&&this._setDisabled(a);return a}},cls:{value:{disabled:"uploader-button-disabled"}},size:{value:{}},flash:{value:{src:"http://a.tbcdn.cn/s/kissy/gallery/form/1.3/uploader/plugins/ajbridge/uploader.swf",
id:"swfUploader",params:{bgcolor:"#fff",wmode:"transparent"},attrs:{},hand:!0,btn:!0}},swfUploader:{value:""}}});return d},{requires:["node","base","../plugins/ajbridge/uploader"]});
KISSY.add("gallery/form/1.3/uploader/index",function(c,j,g,e,d){function a(b,f,d){d=c.mix(c.form.parseConfig(b),d);a.superclass.constructor.call(this,d);this.set("buttonTarget",b);this.set("queueTarget",f);this.set("uploaderConfig",d);this._init()}var b=g.all,f="default,imageUploader,ershouUploader,loveUploader,uploadify,refundUploader,daogouUploader,singleImageUploader".split(",");c.namespace("form");c.form.parseConfig=function(a,d){var f={},e,g=d||"data-config";e=b(a).attr(g);if(!c.isString(e))return{};
try{f=c.JSON.parse(e)}catch(j){c.log("[uploaderRender]:\u8bf7\u68c0\u67e5"+a+"\u4e0a"+g+"\u5c5e\u6027\u5185\u7684json\u683c\u5f0f\u662f\u5426\u7b26\u5408\u89c4\u8303\uff01")}return f};c.extend(a,j,{_init:function(){var a=this,b;""==a.get("theme")?(b=a._initUploader(),a.set("button",b.get("button")),c.later(function(){a.fire("init",{uploader:b,button:b.get("button"),queue:b.get("queue"),auth:b.get("auth")})},500)):a._initThemes(function(c){b=a._initUploader();a.set("button",b.get("button"));c.set("uploader",b);c.set("button",b.get("button"));c.set("queue",b.get("queue"));c.set("auth",
b.get("auth"));c._UploaderRender(function(){c.afterUploaderRender(b);b.restore();a.fire("init",{uploader:b,button:b.get("button"),queue:b.get("queue"),auth:b.get("auth")})})})},_initUploader:function(){var a=this.get("uploaderConfig");c.mix(a,{target:this.get("buttonTarget")});a=new e(a);a.render();this.set("uploader",a);this._auth();return a},_initThemes:function(a){var b=this,f=b.get("theme"),d=b.get("buttonTarget"),e=b.get("themeConfig"),g=c.form.parseConfig(d,"data-theme-config");c.mix(g,e);b.set("themeConfig",
g);f=b._getThemeName(f);c.use(f,function(c,f){var d=b.get("queueTarget"),e;c.mix(g,{queueTarget:d,buttonTarget:b.get("buttonTarget")});e=new f(g);e.on("render",function(){a&&a.call(b,e)});e.render()})},_getThemeName:function(a){var b=a;c.each(f,function(c){c==a&&(b="gallery/form/1.3/uploader/themes/"+a)});return b+="/index"},_auth:function(){var a=this.get("buttonTarget"),b=this.get("uploader"),f=this.get("authConfig"),a=c.form.parseConfig(a,"data-auth");c.mix(a,f);this.set("authConfig",a);if(c.isEmptyObject(a))return!1;
auth=new d(b,{rules:a});b.set("auth",auth);return auth}},{ATTRS:{theme:{value:"default"},themeConfig:{value:{}},buttonTarget:{value:""},queueTarget:{value:""},uploaderConfig:{},authConfig:{value:{}},button:{value:""},queue:{value:""},uploader:{value:""}}});return a},{requires:["base","node","./base","./auth/base"]});
KISSY.add("gallery/form/1.3/uploader/plugins/ajbridge/ajbridge",function(c,j){function g(f,h,l){var f=f.replace(e,""),h=j._normalize(h||{}),i=this,f=e+f,k=function(a){1>a.status?i.fire("failed",{data:a}):(c.mix(i,a),(!a.dynamic||!h.src)&&i.activate())};h.id=h.id||c.guid(d);g.instances[h.id]=i;h.src&&(h.params.allowscriptaccess="always",h.params.flashvars=c.merge(h.params.flashvars,{jsEntry:b,swfID:h.id}));l?i.__args=[f,h,k]:c.later(j.add,a,!1,j,[f,h,k])}var e="#",d="ks-ajb-",a=100,b="KISSY.AJBridge.eventHandler";
c.mix(g,{version:"1.0.15",instances:{},eventHandler:function(a,b){var c=g.instances[a];c&&c.__eventHandler(a,b)},augment:function(a,b){c.isString(b)&&(b=[b]);c.isArray(b)&&c.each(b,function(b){a.prototype[b]=function(){try{return this.callSWF(b,c.makeArray(arguments))}catch(a){this.fire("error",{message:a})}}})}});c.augment(g,c.EventTarget,{init:function(){this.__args&&(j.add.apply(j,this.__args),this.__args=null,delete this.__args)},__eventHandler:function(a,b){var d=b.type;b.id=a;switch(d){case "log":c.log(b.message);
break;default:this.fire(d,b)}},callSWF:function(a,b){b=b||[];try{if(this.swf[a])return this.swf[a].apply(this.swf,b)}catch(c){var d="";0!==b.length&&(d="'"+b.join("','")+"'");return(new Function("self","return self.swf."+a+"("+d+");"))(this)}}});g.augment(g,["activate","getReady","getCoreVersion"]);return window.AJBridge=c.AJBridge=g},{requires:["flash"]});
KISSY.add("gallery/form/1.3/uploader/plugins/ajbridge/uploader",function(c,j,g){function e(d,a){var a=a||{},b={};c.each(["ds","dsp","btn","hand"],function(c){c in a&&(b[c]=a[c])});a.params=a.params||{};a.params.flashvars=c.merge(a.params.flashvars,b);e.superclass.constructor.call(this,d,a)}c.extend(e,g);g.augment(e,"setFileFilters,filter,setAllowMultipleFiles,multifile,browse,upload,uploadAll,cancel,getFile,removeFile,lock,unlock,setBtnMode,useHand,clear".split(","));e.version="1.0.1";g.Uploader=
e;return g.Uploader},{requires:["gallery/flash/1.0/","./ajbridge"]});KISSY.add("gallery/form/1.3/uploader/plugins/coverPic/coverPic",function(c,j,g){function e(){}c.extend(e,g,{render:function(){}},{ATTRS:{}});return e},{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/plugins/filedrop/filedrop",function(c,j,g){var e=j.all,d=c.UA,a=function(c){a.superclass.constructor.call(this,c);this.set("mode",b())},b=function(){if(7<=d.webkit||3.6<=d.firefox)return"supportDrop";if(d.ie)return"notSupportDropIe";if(7>d.webkit||3.6>d.firefox)return"notSupportDrop"};c.mix(a,{event:{AFTER_DROP:"afterdrop"}});c.extend(a,g,{render:function(){var a=this,b=a.get("mode"),d=a.get("uploader");if("flash"==d.get("type"))return c.log("flash\u4e0a\u4f20\u65b9\u5f0f\u4e0d\u652f\u6301\u62d6\u62fd\uff01"),
a.set("isSupport",!1),!1;if("supportDrop"!=b)return c.log("\u8be5\u6d4f\u89c8\u5668\u4e0d\u652f\u6301\u62d6\u62fd\u4e0a\u4f20\uff01"),a.set("isSupport",!1),!1;if(!d)return c.log("\u7f3a\u5c11Uploader\u7684\u5b9e\u4f8b\uff01"),!1;b=a._createDropArea();if(b.length)b.on("click",a._clickHandler,a);d.on("afterDisabledChange",function(b){a[b.newVal&&"hide"||"show"]()});a.fire("afterRender",{buttonTarget:a.get("buttonWrap")})},show:function(){this.get("dropContainer").show()},hide:function(){this.get("dropContainer").hide()},reset:function(){},_createDropArea:function(){var a=this,b=e(a.get("target")),
d=a.get("mode"),d=c.substitute(a.get("tpl")[d],{name:a.get("name")}),d=e(d),i=d.all(".J_ButtonWrap");d.appendTo(b);d.on("dragover",function(a){a.stopPropagation();a.preventDefault()});d.on("drop",function(b){b.stopPropagation();b.preventDefault();a._dropHandler(b)});a.set("dropContainer",d);a.set("buttonWrap",i);a._setStyle();return d},_setStyle:function(){var a=this.get("dropContainer");if(!a.length)return!1;a.parent().css("position","relative");a.css({position:"absolute",top:"0",left:"0",width:"100%",
height:"100%",zIndex:"1000"})},_clickHandler:function(a){e(a.target);this.get("uploader").get("button").get("fileInput").fire("click")},_dropHandler:function(b){var d=a.event,b=b.originalEvent.dataTransfer.files,e=[],i=this.get("uploader");if(!b.length||""==i)return!1;c.each(b,function(a){c.isObject(a)&&e.push({name:a.name,type:a.type,size:a.size,data:a})});this.fire(d.AFTER_DROP,{files:e});i._select({files:e})},_setDisabled:function(){}},{ATTRS:{target:{value:""},uploader:{value:""},dropContainer:{value:""},
isSupport:{value:!0},tpl:{value:{supportDrop:'<div class="drop-wrapper"><p>\u76f4\u63a5\u62d6\u62fd\u56fe\u7247\u5230\u8fd9\u91cc\uff0c</p><p class="J_ButtonWrap">\u6216\u8005</p></div>',notSupportDropIe:'<div class="drop-wrapper"><p>\u60a8\u7684\u6d4f\u89c8\u5668\u53ea\u652f\u6301\u4f20\u7edf\u7684\u56fe\u7247\u4e0a\u4f20\uff0c</p><p class="suggest J_ButtonWrap">\u63a8\u8350\u4f7f\u7528chrome\u6d4f\u89c8\u5668\u6216firefox\u6d4f\u89c8\u5668</p></div>',notSupportDrop:'<div class="drop-wrapper"><p>\u60a8\u7684\u6d4f\u89c8\u5668\u53ea\u652f\u6301\u4f20\u7edf\u7684\u56fe\u7247\u4e0a\u4f20\uff0c</p><p class="suggest J_ButtonWrap">\u63a8\u8350\u5347\u7ea7\u60a8\u7684\u6d4f\u89c8\u5668</p></div>'}},name:{value:"",setter:function(){}},disabled:{value:!1,setter:function(a){this._setDisabled(a);return a}},cls:{disabled:"drop-area-disabled"}}});
return a},{requires:["node","base"]});
KISSY.add("'gallery/form/1.3/uploader/plugins/imagePreview/imagePreview'",function(c){function j(){var e="filename";window.URL&&window.URL.createObjectURL||window.webkitURL&&window.webkitURL.createObjectURL||window.FileReader?e="html5":7===c.UA.ie||8===c.UA.ie?e="filter":6===c.UA.ie&&(e="default");return e}var g;!function(){var e={};g={add:function(d,a){e[d]?c.mix(e[d],a):e[d]=a;e[d].type=d},use:function(d){return c.mix(e["default"],e[d])}}}();g.add("default",{getData:function(c){return[c.value]},
show:function(c,d){var a=this,b=new Image;b.src=c;document.all?(b.onreadystatechange=function(){if("loaded"==b.readyState||"complete"==b.readyState)d(b,a.type),b.onreadystatechange=null},b.onreadystatechange()):b.onload=function(){d(b,a.type);b.onload=null}}});g.add("html5",{getData:function(c){for(var d=[],a=0;a<c.files.length;a++)0<=c.files[a].type.indexOf("image")&&d.push(c.files[a]);return d},show:function(c,d){var a=new Image;if(window.URL&&window.URL.createObjectURL)a.src=window.URL.createObjectURL(c);
else if(window.webkitURL&&window.webkitURL.createObjectURL)a.src=window.webkitURL.createObjectURL(c);else{var b=new FileReader;b.onload=function(b){a.src=b.target.result};b.readAsDataURL(c)}d(a,this.type)}});g.add("filter",{getData:function(c){c.select();try{return[document.selection.createRange().text]}finally{document.selection.empty()}return[]},show:function(e,d){var a=6==c.UA.ie||7==c.UA.ie?"http://img04.taobaocdn.com/tps/i4/T1Ao_pXfVpXXc6Yc2r-1-1.gif":"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";
if(!this._preload){var b=this._preload=document.createElement("div");c.DOM.css(b,{width:"1px",height:"1px",visibility:"hidden",position:"absolute",left:"-9999px",top:"-9999px",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='image')"});var f=document.body;f.insertBefore(b,f.childNodes[0])}var f=new Image,b=this._preload,h=e.replace(/[)'"%]/g,function(a){return escape(escape(a))});try{b.filters.item("DXImageTransform.Microsoft.AlphaImageLoader").src=h}catch(g){return}f.style.filter=
"progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='scale',src=\""+h+'")';f.style.width=b.offsetWidth;f.style.height=b.offsetHeight;f.src=a;f.width=b.offsetWidth;f.height=b.offsetHeight;d(f,this.type,b.offsetWidth,b.offsetHeight)}});g.add("filename",{getData:function(c){var d=[];if(c.files)for(var a=0;a<c.files.length;a++)d.push(c.files[a].name);else d.push(c.value);return d},show:function(e,d){d(c.DOM.create(e),this.type)}});return function(c,d){for(var a=g.use(j(c)),b=a.getData(c),
f=0;f<b.length;f++)a.show(b[f],d)}});
KISSY.add("gallery/form/1.3/uploader/plugins/preview/preview",function(c,j){function g(a,c){if(!a)return!1;"filter"!=b?a.src=c||f:(a.src=f,c&&(c=c.replace(/[)'"%]/g,function(a){return escape(escape(a))}),a.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod='scale',src='"+c+"')",a.zoom=1));return!0}function e(d){this.config=c.mix({maxWidth:40,maxHeight:40},d);c.log(a+"Preview initialized. The preview mode is "+b)}var d=document,a="[Plugin: Preview] ",b=function(){var a="";
if("undefined"===typeof window.FileReader)switch(c.UA.shell){case "firefox":a="domfile";break;case "ie":switch(c.UA.ie){case 6:a="simple";break;default:a="filter"}}else a="html5";return a}(),f=8>c.UA.ie?"http://a.tbcdn.cn/p/fp/2011a/assets/space.gif":"data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==";c.augment(e,c.EventTarget,{show:function(d,f){if("html5"!=b||!f||!f.length)return!1;var e=this,g=new FileReader;g.onload=function(a){a=e.data=a.target.result;e.fire(void 0,
{data:a,mode:b});f.attr("src",a);e.fire("showed",{img:a})};g.onerror=function(){c.log(a+"File Reader Error. Your browser may not fully support html5 file api","warning");e.fire("error")};g.readAsDataURL(d)},preview:function(f,e){var f=j.get(f),e=j.get(e),i=this,k=function(){i.fire(void 0,{data:i.data,mode:b});e&&(g(e,i.data),i.fire("showed",{img:e}))};i.data=void 0;if(f){c.log(a+"One file selected. Getting data...");switch(b){case "domfile":i.data=f.files[0].getAsDataURL();break;case "filter":f.select();
try{i.data=d.selection.createRange().text}catch(m){c.log(a+"Get image data error, the error is: "),c.log(m,"dir")}finally{d.selection.empty()}i.data||(i.data=f.value);break;case "html5":var n=new FileReader;n.onload=function(a){i.data=a.target.result;k()};n.onerror=function(){c.log(a+"File Reader Error. Your browser may not fully support html5 file api","warning");i.fire("error")};f.files&&n.readAsDataURL(f.files[0]);break;default:i.data=f.value}i.data?k():"html5"!=b&&(c.log(a+"Retrive Data error."),
g(e),i.fire("error"))}else c.log(a+"File Input Element does not exists.");return i.data}});return e},{requires:["dom","event"]});
KISSY.add("gallery/form/1.3/uploader/plugins/progressBar/progressBar",function(c,j,g){function e(a,b){b=c.merge({wrapper:d(a)},b);e.superclass.constructor.call(this,b)}var d=j.all;c.mix(e,{tpl:{DEFAULT:'<div class="ks-progress-bar-value" data-value="{value}"></div>'},cls:{PROGRESS_BAR:"ks-progress-bar",VALUE:"ks-progress-bar-value"},event:{RENDER:"render",CHANGE:"change",SHOW:"show",HIDE:"hide"}});c.extend(e,g,{render:function(){var a=this.get("wrapper"),b=this.get("width");if(!a.length)return!1;
a.addClass(e.cls.PROGRESS_BAR).width(b);this._addAttr();!this.get("visible")&&this.hide();this.set("bar",this._create());this.fire(e.event.RENDER)},show:function(){var a=this;a.get("wrapper").fadeIn(a.get("duration"),function(){a.set("visible",!0);a.fire(e.event.SHOW,{visible:!0})})},hide:function(){var a=this;a.get("wrapper").fadeOut(a.get("duration"),function(){a.set("visible",!1);a.fire(e.event.HIDE,{visible:!1})})},_create:function(){var a=this.get("wrapper"),b=this.get("value"),f=this.get("tpl"),
b=c.substitute(f,{value:b});a.html("");return d(b).appendTo(a)},_addAttr:function(){var a=this.get("wrapper"),b=this.get("value");a.attr("role","progressbar");a.attr("aria-valuemin",0);a.attr("aria-valuemax",100);a.attr("aria-valuenow",b);return this}},{ATTRS:{wrapper:{value:""},bar:{value:""},width:{value:"auto"},value:{value:0,setter:function(a){var b=this,c=b.get("wrapper"),d=b.get("bar"),g=b.get("speed"),i;100<a&&(a=100);0>a&&(a=0);i=c.width()*(a/100);d.animate({width:i+"px"},g,"none",function(){c.attr("aria-valuenow",
a);d.attr("data-value",a);b.fire(e.event.CHANGE,{value:a,width:i})});return a}},visible:{value:!0},duration:{value:0.3},tpl:{value:e.tpl.DEFAULT},speed:{value:0.2}}});return e},{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/queue",function(c,j,g){function e(c){e.superclass.constructor.call(this,c)}c.mix(e,{tpl:{DEFAULT:'<li id="queue-file-{id}" class="clearfix" data-name="{name}"><div class="f-l sprite file-icon"></div><div class="f-l">{name}</div><div class="f-l file-status J_FileStatus"></div></li>'},event:{ADD:"add",ADD_FILES:"addFiles",REMOVE:"remove",CLEAR:"clear",FILE_STATUS:"statusChange",UPDATE_FILE:"updateFile",RESTORE:"restore"},status:{WAITING:"waiting",START:"start",PROGRESS:"progress",
SUCCESS:"success",CANCEL:"cancel",ERROR:"error",RESTORE:"restore"},cls:{QUEUE:"ks-uploader-queue"},hook:{STATUS:".J_FileStatus"},FILE_ID_PREFIX:"file-"});c.extend(e,g,{add:function(d,a){var b=this,f={};0<d.length?(f=[],c.each(d,function(a){f.push(b._addFile(a))})):f=b._addFile(d);a&&a.call(b);return f},_addFile:function(d,a){if(!c.isObject(d))return c.log("[uploader-queue]:_addFile()\u53c2\u6570file\u4e0d\u5408\u6cd5\uff01"),!1;var b=this._setAddFileData(d),f=this.getFileIndex(b.id),h=this.get("fnAdd");c.isFunction(h)&&(b=h(f,
b));this.fire(e.event.ADD,{index:f,file:b,uploader:this.get("uploader")});a&&a.call(this,f,b);return b},remove:function(d,a){var b=this.get("files"),f;c.isString(d)&&(d=this.getFileIndex(d));f=b[d];if(!c.isObject(f))return c.log("[uploader-queue]:remove()\u4e0d\u5b58\u5728index\u4e3a"+d+"\u7684\u6587\u4ef6\u6570\u636e"),!1;b=c.filter(b,function(a,b){return b!==d});this.set("files",b);this.fire(e.event.REMOVE,{index:d,file:f});a&&a.call(this,d,f);return f},clear:function(){function c(){b=a.get("files");if(!b.length)return a.fire(e.event.CLEAR),
!1;a.remove(0,function(){c()})}var a=this,b;c()},fileStatus:function(d,a,b){if(!c.isNumber(d))return!1;var f=this.getFile(d),h=this.get("theme"),g;if(!f)return!1;g=f.status;if(!a)return g;if(g==a)return this;this.updateFile(d,{status:a});g="_"+a+"Handler";h&&c.isFunction(h[g])&&(b=c.merge({uploader:this.get("uploader"),index:d,file:f,id:f.id},b),h[g].call(h,b));this.fire(e.event.FILE_STATUS,{index:d,status:a,args:b,file:f});return this},getFile:function(d){if(!c.isNumber(d))return!1;d=this.get("files")[d];
c.isPlainObject(d)||(c.log("getFile():\u6587\u4ef6\u6570\u636e\u4e3a\u7a7a\uff01"),d={});return d},getFileIndex:function(d){var a=this.get("files"),b=-1;c.each(a,function(a,c){if(a.id==d)return b=c,!0});return b},updateFile:function(d,a){if(!c.isNumber(d))return!1;if(!c.isObject(a))return c.log("[uploader-queue]:updateFile()\u7684data\u53c2\u6570\u6709\u8bef\uff01"),!1;var b=this.get("files"),f=this.getFile(d);if(!f)return!1;c.mix(f,a);b[d]=f;this.set("files",b);this.fire(e.event.UPDATE_FILE,{index:d,file:f});return f},getIndexs:function(d){var a=this.get("files"),
b,f=[];if(!a.length)return f;c.each(a,function(a,e){c.isObject(a)&&(b=a.status,b==d&&f.push(e))});return f},getFiles:function(d){var a=this.get("files"),b=[];if(!a.length)return[];c.each(a,function(a){a&&a.status==d&&b.push(a)});return b},_setAddFileData:function(d){var a=this.get("files");if(!c.isObject(d))return c.log("[uploader-queue]:_updateFileData()\u53c2\u6570file\u4e0d\u5408\u6cd5\uff01"),!1;d.id||(d.id=c.guid(e.FILE_ID_PREFIX));d.size&&c.convertByteSize&&(d.textSize=c.convertByteSize(d.size));d.status="";a.push(d);return d}},
{ATTRS:{fnAdd:{value:""},files:{value:[]},uploader:{value:""},theme:{value:""}}});return e},{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/theme",function(c,j,g){function e(a){e.superclass.constructor.call(this,a)}var d=j.all;c.extend(e,g,{render:function(){var a=this;a._LoaderCss(function(){a._addThemeCssName();a.fire("render")})},afterUploaderRender:function(){},_getStatusWrapper:function(a){return a&&a.children(".J_FileStatus")||d("")},displayFile:function(a,b,c){var d=this,e=d.get("duration");if(!b||!b.length)return!1;b[a&&"fadeIn"||"fadeOut"](e,function(){c&&c.call(d)})},_waitingHandler:function(){},
_startHandler:function(){},_progressHandler:function(){},_successHandler:function(){},_errorHandler:function(){},_restoreHandler:function(){},_UploaderRender:function(a){this._initQueue();this._loadPlugins(a)},_addThemeCssName:function(){var a=this.get("name"),b=d(this.get("queueTarget")),c=d(this.get("buttonTarget"));if(""==a)return!1;b.length&&b.addClass(a+"-queue");c.addClass(a+"-button")},_initQueue:function(){var a=this,b=a.get("queue");b.set("fnAdd",function(b,c){return a._addCallback(b,c)});
b.set("theme",a);b.on("add",a._addFileHandler,a);b.on("remove",a._removeFileHandler,a);b.on("statusChange",function(b){a._setStatusVisibility(b)});return b},_LoaderCss:function(a){var b=this,d=b.get("cssUrl");if(""==d)return a.call(b),!1;c.use(d,function(){c.log(d+"\u52a0\u8f7d\u6210\u529f\uff01");a.call(b)})},_addCallback:function(a,b){var c=this.get("queue"),d=this._appendFileDom(b);c.updateFile(a,{target:d,statusWrapper:this._getStatusWrapper(d)});c.fileStatus(a,"waiting");this.displayFile(!0,d);this._bindTriggerEvent(a,
b);return c.getFile(a)},_removeFileHandler:function(a){this.displayFile(!1,a.file.target)},_bindTriggerEvent:function(a,b){var f=this.get("queue"),e=this.get("uploader"),g=b.id,i=d(".J_Upload_"+g),j=d(".J_Cancel_"+g),m=d(".J_Del_"+g);i.on("click",function(b){b.preventDefault();if(!c.isObject(e))return!1;e.upload(a)});j.on("click",function(b){b.preventDefault();e.cancel(a)});m.on("click",function(a){a.preventDefault();f.remove(g)})},_setStatusVisibility:function(a){var b=a.file.statusWrapper,a=a.file,
d=a.status;if(!b||!b.length)return c.log("\u72b6\u6001\u5bb9\u5668\u5c42\u4e0d\u5b58\u5728\uff01"),!1;b.children(".status").hide();b.children("."+d+"-status").show();var e=a.target;c.each("waiting,start,uploading,progress,error,success".split(","),function(a){e.removeClass(a)});e.addClass(d)},_appendFileDom:function(a){var b=this.get("fileTpl"),f=d(this.get("queueTarget"));if(!f.length)return!1;b=c.substitute(b,a);return d(b).hide().appendTo(f).data("data-file",a)},_loadPlugins:function(a){var b=this,d=b.get("plugins"),e=b.get("oPlugin"),g=
[];if(!d.length)return a&&a.call(b,e),!1;c.each(d,function(a){g.push("gallery/form/1.3/uploader/plugins/"+a+"/"+a)});c.use(g.join(","),function(){c.each(arguments,function(a,b){1<=b&&(e[d[b-1]]=a)});b.set("oPlugin",e);a&&a.call(b,e)})}},{ATTRS:{name:{value:""},cssUrl:{value:""},fileTpl:{value:""},plugins:{value:[]},oPlugin:{value:{}},queueTarget:{value:""},duration:{value:0.3},queue:{value:""},uploader:{value:""},button:{value:""},auth:{value:""}}});return e},{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/type/ajax",function(c,j,g){function e(c){e.superclass.constructor.call(this,c)}c.mix(e,{event:c.merge(g.event,{PROGRESS:"progress"})});c.extend(e,g,{upload:function(d){if(!d)return c.log("[uploader-AjaxType]:upload()\uff0cfileData\u53c2\u6570\u6709\u8bef\uff01"),!1;this._setFormData();this._addFileData(d);this.send();return this},stop:function(){var d=this.get("xhr");if(!c.isObject(d))return c.log("[uploader-AjaxType]:stop()\uff0cio\u503c\u9519\u8bef\uff01"),!1;d.abort();this.fire(e.event.STOP);return this},send:function(){var c=
this,a=c.get("action"),b=c.get("formData"),f=new XMLHttpRequest;f.upload.addEventListener("progress",function(a){c.fire(e.event.PROGRESS,{loaded:a.loaded,total:a.total})});f.onload=function(){var a=c._processResponse(f.responseText);c.fire(e.event.SUCCESS,{result:a})};f.open("POST",a,!0);b.append("type","ajax");f.send(b);c._setFormData();c.set("xhr",f);return c},_setFormData:function(){try{this.set("formData",new FormData),this._processData()}catch(d){c.log("[uploader-AjaxType]:something error when reset FormData."),
c.log(d,"dir")}},_processData:function(){var d=this.get("data"),a=this.get("formData");c.each(d,function(b,c){a.append(c,b)});this.set("formData",a)},_addFileData:function(d){if(!c.isObject(d))return c.log("[uploader-AjaxType]:_addFileData()\uff0cfile\u53c2\u6570\u6709\u8bef\uff01"),!1;var a=this.get("formData"),b=this.get("fileDataName");a.append(b,d);this.set("formData",a)}},{ATTRS:{formData:{value:""},ajaxConfig:{value:{type:"post",processData:!1,cache:!1,dataType:"json",contentType:!1}},xhr:{value:""},fileDataName:{value:""},
form:{value:{}},fileInput:{value:""}}});return e},{requires:["node","./base"]});
KISSY.add("gallery/form/1.3/uploader/type/base",function(c,j,g){function e(c){e.superclass.constructor.call(this,c)}c.mix(e,{event:{START:"start",STOP:"stop",SUCCESS:"success",ERROR:"error"}});c.extend(e,g,{upload:function(){},stop:function(){},_processResponse:function(d){var a=this.get("filter"),b={};""!=a&&(d=a.call(this,d));if(c.isString(d))try{b=c.JSON.parse(d),b=this._fromUnicode(b)}catch(f){d+="\uff0c\u8fd4\u56de\u7ed3\u679c\u96c6responseText\u683c\u5f0f\u4e0d\u5408\u6cd5\uff01",c.log(d),this.fire("error",{status:-1,result:{msg:d}})}else c.isObject(d)&&
(b=this._fromUnicode(d));c.log("\u670d\u52a1\u5668\u7aef\u8f93\u51fa\uff1a"+c.JSON.stringify(b));return b},_fromUnicode:function(d){function a(b){c.each(b,function(d,e){c.isObject(b[e])?a(b[e]):b[e]=c.isString(d)&&c.fromUnicode(d)||d})}if(!c.isObject(d))return d;a(d);return d}},{ATTRS:{action:{value:""},data:{value:{}},filter:{value:""}}});return e},{requires:["node","base"]});
KISSY.add("gallery/form/1.3/uploader/type/flash",function(c,j,g){function e(c){e.superclass.constructor.call(this,c);this.isHasCrossdomain();this._init()}if(c.FlashType)return c.FlashType;c.mix(e,{event:c.merge(g.event,{SWF_READY:"swfReady",PROGRESS:"progress"})});c.extend(e,g,{_init:function(){var d=this,a=d.get("swfUploader");if(!a)return c.log("[uploader-FlashType]:swfUploader\u5bf9\u8c61\u4e3a\u7a7a\uff01"),!1;a.on("contentReady",function(){d.fire(e.event.SWF_READY)},d);a.on("uploadStart",d._uploadStartHandler,d);a.on("uploadProgress",
d._uploadProgressHandler,d);a.on("uploadCompleteData",d._uploadCompleteDataHandler,d);a.on("uploadError",d._uploadErrorHandler,d)},upload:function(d){var a=this.get("swfUploader"),b=this.get("action"),f=this.get("data"),e=this.get("fileDataName");e||(e="Filedata");this.set("uploadingId",d);c.mix(f,{type:"flash"});a.upload(d,b,"POST",f,e);return this},stop:function(){var c=this.get("swfUploader"),a=this.get("uploadingId");""!=a&&(c.cancel(a),this.fire(e.event.STOP,{id:a}));return this},_uploadStartHandler:function(c){this.fire(e.event.START,
{file:c.file})},_uploadProgressHandler:function(d){c.mix(d,{loaded:d.bytesLoaded,total:d.bytesTotal});c.log("[uploader-FlashType]:\u5df2\u7ecf\u4e0a\u4f20\u5b57\u8282\u6570\u4e3a\uff1a"+d.bytesLoaded);this.fire(e.event.PROGRESS,{loaded:d.loaded,total:d.total})},_uploadCompleteDataHandler:function(c){c=this._processResponse(c.data);this.set("uploadingId","");this.fire(e.event.SUCCESS,{result:c})},_uploadErrorHandler:function(c){this.set("uploadingId","");this.fire(e.event.ERROR,{msg:c.msg})},isHasCrossdomain:function(){c.io({url:"http://"+location.hostname+
"/crossdomain.xml",dataType:"xml",error:function(){c.log("\u7f3a\u5c11crossdomain.xml\u6587\u4ef6\u6216\u8be5\u6587\u4ef6\u4e0d\u5408\u6cd5\uff01")}})}},{ATTRS:{action:{value:"",getter:function(d){if(!/^http/.test(d))var a=location.href.split("/"),d=c.filter(a,function(b,c){return c<a.length-1}).join("/")+"/"+d;return d}},swfUploader:{value:""},uploadingId:{value:""}}});return c.FlashType=e},{requires:["node","./base"]});
KISSY.add("gallery/form/1.3/uploader/type/iframe",function(c,j,g){function e(a){e.superclass.constructor.call(this,a)}var d=j.all;c.mix(e,{tpl:{IFRAME:'<iframe src="javascript:false;" name="{id}" id="{id}" border="no" width="1" height="1" style="display: none;" />',FORM:'<form method="post" enctype="multipart/form-data" action="{action}" target="{target}" style="visibility: hidden;">{hiddenInputs}</form>',HIDDEN_INPUT:'<input type="hidden" name="{name}" value="{value}" />'},event:c.mix(g.event,{CREATE:"create",
REMOVE:"remove"})});c.extend(e,g,{upload:function(a){a=d(a);if(!a.length)return!1;this.fire(e.event.START,{input:a});this.set("fileInput",a);this._create();a=this.get("form");if(!a)return c.log("[uploader-iframeType]:form\u8282\u70b9\u4e0d\u5b58\u5728\uff01"),!1;a.getDOMNode().submit()},stop:function(){this.get("iframe").attr("src",'javascript:"<html></html>";');this._remove();this.fire(e.event.STOP);this.fire(e.event.ERROR,{status:"abort",msg:"\u4e0a\u4f20\u5931\u8d25\uff0c\u539f\u56e0\uff1aabort"});return this},dataToHidden:function(a){if(!c.isObject(a)||c.isEmptyObject(a))return"";
var b="",d=this.get("tpl").HIDDEN_INPUT;if(!c.isString(d))return"";for(var e in a)b+=c.substitute(d,{name:e,value:a[e]});return b},_createIframe:function(){var a="ks-uploader-iframe-"+c.guid(),b=this.get("tpl"),f=b.IFRAME,e=this.get("iframe");if(!c.isEmptyObject(e))return e;if(!c.isString(f))return c.log("[uploader-iframeType]:iframe\u7684\u6a21\u677f\u4e0d\u5408\u6cd5\uff01"),!1;if(!c.isString(a))return c.log("[uploader-iframeType]:id\u5fc5\u987b\u5b58\u5728\u4e14\u4e3a\u5b57\u7b26\u4e32\u7c7b\u578b\uff01"),!1;b=c.substitute(b.IFRAME,{id:a});b=d(b);b.on("load",this._iframeLoadHandler,this);
d("body").append(b);this.set("id",a);this.set("iframe",b);return b},_iframeLoadHandler:function(a){var b=a.target,a=e.event.ERROR,b=b.contentDocument||window.frames[b.id].document;if(!b||!b.body)return this.fire(a,{msg:"\u670d\u52a1\u5668\u7aef\u8fd4\u56de\u6570\u636e\u6709\u95ee\u9898\uff01"}),!1;a=b.body.innerHTML;if(""==a)return!1;a=this._processResponse(a);this.fire(e.event.SUCCESS,{result:a});this._remove()},_createForm:function(){var a=this.get("id"),b=this.get("tpl").FORM,f=this.get("data"),e=this.get("action"),g=this.get("fileInput");if(!c.isString(b))return c.log("[uploader-iframeType]:form\u6a21\u677f\u4e0d\u5408\u6cd5\uff01"),
!1;if(!c.isString(e))return c.log("[uploader-iframeType]:action\u53c2\u6570\u4e0d\u5408\u6cd5\uff01"),!1;f=this.dataToHidden(f);f+=this.dataToHidden({type:"iframe"});a=c.substitute(b,{action:e,target:a,hiddenInputs:f});g=d(a).append(g);d("body").append(g);this.set("form",g);return g},_create:function(){var a=this._createIframe(),b=this._createForm();this.fire(e.event.CREATE,{iframe:a,form:b})},_remove:function(){var a=this.get("form");if(!a)return!1;a.remove();this.reset("form");this.fire(e.event.REMOVE,{form:a})}},{ATTRS:{tpl:{value:e.tpl},
id:{value:"ks-uploader-iframe-"+c.guid()},iframe:{value:{}},form:{value:""},fileInput:{value:""}}});return e},{requires:["node","./base"]});
KISSY.add("gallery/form/1.3/uploader/urlsInput",function(c,j,g){function e(a,b){e.superclass.constructor.call(this,b);this.set("wrapper",d(a))}var d=j.all;c.mix(e,{TPL:'<input type="hidden" id="{name}" name="{name}" value="{value}" />'});c.extend(e,g,{render:function(){var a=this.get("wrapper"),b=this.get("name"),b=document.getElementsByName(b)[0];if(!c.isObject(a))return c.log("[uploader-urlsInput]:container\u53c2\u6570\u4e0d\u5408\u6cd5\uff01"),!1;b?(c.log("[uploader-urlsInput]:urls input found"),this.set("input",d(b))):this._create();
return this},add:function(a){if(!c.isString(a))return c.log("[uploader-urlsInput]:add()\u7684url\u53c2\u6570\u4e0d\u5408\u6cd5\uff01"),!1;var b=this.get("urls"),d=this.isExist(a);""==b[0]&&(b=[]);if(d)return c.log("[uploader-urlsInput]:add()\uff0c\u6587\u4ef6\u8def\u5f84\u5df2\u7ecf\u5b58\u5728\uff01"),this;b.push(a);this.set("urls",b);this._val();return this},remove:function(a){if(!a)return!1;var b=this.get("urls"),d=this.isExist(a),e=RegExp(a);if(!d)return c.log("[uploader-urlsInput]:remove()\uff0c\u4e0d\u5b58\u5728\u8be5\u6587\u4ef6\u8def\u5f84\uff01"),!1;b=c.filter(b,function(a){return!e.test(a)});this.set("urls",b);this._val();
return b},parse:function(){var a=this.get("input");if(a){var a=d(a).val(),b=this.get("split");if(""==a)return[];a=a.split(b);this.set("urls",a);return a}c.log("[uploader-urlsInput]:cannot find urls input.");return[]},_val:function(){var a=this.get("urls"),b=this.get("input"),c=this.get("split"),a=a.join(c);b.val(a);return a},isExist:function(a){var b=!1,d=this.get("urls"),e=RegExp(a);if(!d.length)return!1;c.each(d,function(a){if(e.test(a))return b=!0});return b},_create:function(){var a=this.get("wrapper"),
b=this.get("tpl"),f=this.get("name"),e=this.get("urls");if(!a||0>=a.length)return c.log("[uploader-urlsInput]:UrlsInput container not specified!","warn"),!1;if(!c.isString(b)||!c.isString("name"))return c.log("[uploader-urlsInput]:_create()\uff0ctpl\u548cname\u5c5e\u6027\u4e0d\u5408\u6cd5\uff01"),!1;b=d(c.substitute(b,{name:f,value:e}));a.append(b);this.set("input",b);c.log("[uploader-urlsInput]:input created.");return b}},{ATTRS:{name:{value:""},urls:{value:[]},tpl:{value:e.TPL},split:{value:",",setter:function(a){this._val();return a}},
input:{value:""},wrapper:{value:""}}});return e},{requires:["node","base"]});
